# -*- coding: utf-8 -*-
"""TA047R_TP1_GRUPO02_ENTREGA_EJ2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10Ah__nEu8AXZ8ovQo2ylpy3ll310XJuU

# Trabajo Práctico 1 - Grupo 02

### Ejercicio 2

Integrantes:
- Bermudez, Agustin
- Calderón, Tiago
- Gonzalez Pautaso, Mateo
- Moreyra, Santiago
- Nieves, Maylen

## 1. Análisis exploratorio y preprocesamiento

### Carga de datos
Para el desarrollo de este ejercicio se utilizan datos de observaciones meteorológicas diarias provenientes de numerosas estaciones ubicadas a lo largo de Australia, con el objetivo de predecir si lloverá al día siguiente (`RainTomorrow`) a partir de las condiciones climáticas registradas en el día actual.

#### Sobre el dataset
Los datos corresponden a observaciones meteorológicas diarias registradas en distintas estaciones de Australia durante aproximadamente 10 años, obtenidos desde [Kaggle](https://www.kaggle.com/datasets/jsphyg/weather-dataset-rattle-package?resource=download).

El archivo está en formato `.csv` y se carga usando el método específico para ello de `pandas`.

Para este ejercicio se filtran únicamente las estaciones pertenecientes a los territorios asignados: **Queensland**, **Nueva Gales del Sur** y **Territorio de la Capital Australiana (ACT)**.

Cada fila representa las observaciones de un día en una estación meteorológica particular e incluye variables como temperatura, humedad, presión atmosférica, dirección y velocidad del viento, entre otras. La variable objetivo es `RainTomorrow`, que indica si llovió al día siguiente (`Yes`/`No`).

Descripción de variables

Variables cuantitativas (numéricas continuas)
- **MinTemp:** Temperatura mínima del día (°C)
- **MaxTemp:** Temperatura máxima del día (°C)
- **Rainfall:** Cantidad de lluvia registrada en el día (mm)
- **Evaporation:** Evaporación registrada en las 24 horas hasta las 9am (mm)
- **Sunshine:** Horas de sol brillante en el día
- **WindGustSpeed:** Velocidad de la ráfaga de viento más fuerte en las 24 horas hasta medianoche (km/h)
- **WindSpeed9am:** Velocidad del viento promediada en los 10 minutos previos a las 9am (km/h)
- **WindSpeed3pm:** Velocidad del viento promediada en los 10 minutos previos a las 3pm (km/h)
- **Humidity9am:** Humedad relativa a las 9am (%)
- **Humidity3pm:** Humedad relativa a las 3pm (%)
- **Pressure9am:** Presión atmosférica reducida al nivel del mar a las 9am (hPa)
- **Pressure3pm:** Presión atmosférica reducida al nivel del mar a las 3pm (hPa)
- **Cloud9am:** Fracción del cielo cubierta por nubes a las 9am, medida en oktas (0-8)
- **Cloud3pm:** Fracción del cielo cubierta por nubes a las 3pm, medida en oktas (0-8)
- **Temp9am:** Temperatura a las 9am (°C)
- **Temp3pm:** Temperatura a las 3pm (°C)

Variables cualitativas (categóricas)
- **Date:** Fecha de la observación
- **Location:** Nombre de la estación meteorológica
- **WindGustDir:** Dirección de la ráfaga de viento más fuerte (16 puntos cardinales)
- **WindDir9am:** Dirección del viento a las 9am (16 puntos cardinales)
- **WindDir3pm:** Dirección del viento a las 3pm (16 puntos cardinales)
- **RainToday:** Variable binaria: 1 si la precipitación supera 1mm, 0 en caso contrario
- **RainTomorrow:** Variable objetivo binaria: indica si llovió al día siguiente (Yes/No)
"""

import pandas as pd
import numpy as np

#Visualizaciones
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn import tree
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, recall_score, precision_score, f1_score
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import GridSearchCV
from sklearn.preprocessing import LabelEncoder

pd.set_option('display.float_format', '{:.2f}'.format)

df = pd.read_csv('weatherAUS.csv')

territorios = ['Albury', 'BadgerysCreek', 'Cobar', 'CoffsHarbour', 'Moree', 'Newcastle',
               'NorahHead', 'Penrith', 'Richmond', 'Sydney', 'SydneyAirport',
               'WaggaWagga', 'Williamtown', 'Wollongong',  # Nueva Gales del Sur
               'Canberra', 'Tuggeranong', 'MountGinini',   # Territorio de la Capital
               'Brisbane', 'Cairns', 'GoldCoast', 'Townsville']  # Queensland

df = df[df['Location'].isin(territorios)].reset_index(drop=True)

# Ver las primeras filas
df.head(5)

"""### Estudio inicial del dataframe"""

print(df.dtypes)
print(f"\nDimensiones: {df.shape[0]} filas x {df.shape[1]} columnas")

"""El dataset filtrado contiene observaciones meteorológicas diarias de 21 estaciones distribuidas en Queensland, Nueva Gales del Sur y el Territorio de la Capital. Cada fila representa un día en una estación particular.
Las variables se pueden clasificar en:

- **Numéricas continuas:** temperaturas, lluvia, evaporación, horas de sol, velocidad del viento, humedad, presión atmosférica, nubosidad.
- **Categóricas:** dirección del viento (`WindGustDir`, `WindDir9am`, `WindDir3pm`), lluvia hoy (`RainToday`) y lluvia mañana (`RainTomorrow`, variable objetivo).
- **Fecha:** `Date`, actualmente en formato object.
"""

# Convertir Date a datetime
df['Date'] = pd.to_datetime(df['Date'])

# Ver rango temporal
print(f"Período: {df['Date'].min()} → {df['Date'].max()}")
print(f"Estaciones disponibles:\n{df['Location'].value_counts()}")

"""### Análisis de valores faltantes"""

nulos = df.isnull().sum()
pct_nulos = (nulos / len(df) * 100).round(2)

resumen_nulos = pd.DataFrame({
    'Nulos': nulos,
    '% Nulos': pct_nulos
}).query('Nulos > 0').sort_values('% Nulos', ascending=False)

# Visualización
plt.figure(figsize=(10, 5))
sns.barplot(x=resumen_nulos.index, y=resumen_nulos['% Nulos'], color='steelblue')
plt.xticks(rotation=45, ha='right')
plt.title('Porcentaje de valores faltantes por variable')
plt.ylabel('% Nulos')
plt.xlabel('Variable')
plt.tight_layout()
plt.show()

"""A partir del gráfico se identifican tres grupos de variables según su porcentaje de nulos:

- `Sunshine` (62.43%) y `Evaporation` (53.32%) superan el 50% de valores faltantes. Imputar más de la mitad de los datos de una variable introduciría más ruido que información real. Además, estas mediciones no son registradas de forma estándar por todas las estaciones meteorológicas, lo que explica estructuralmente su ausencia. Se decide eliminarlas.
- `Cloud9am` (44.78%) y `Cloud3pm` (45.67%) tienen una proporción alta pero por debajo del umbral. Se imputan con la mediana por estación.
- El resto de las variables numéricas presentan menos del 16% de nulos y se imputan también con la mediana por estación (`Location`), ya que el clima varía significativamente entre regiones y usar una mediana global introduciría sesgo.
- `RainToday` y `RainTomorrow` (2.38%) se tratan por separado: al ser la variable objetivo y su análogo del día actual, no es válido imputarlas, por lo que se eliminan las filas con valores nulos en estas columnas.
"""

# Eliminar columnas con más del 50% de nulos
cols_eliminar = pct_nulos[pct_nulos > 50].index.tolist()
print(f"Columnas eliminadas: {cols_eliminar}")
df = df.drop(columns=cols_eliminar)

# Imputar numéricas con mediana por Location
cols_numericas = df.select_dtypes(include='float64').columns
for col in cols_numericas:
    df[col] = df.groupby('Location')[col].transform(
        lambda x: x.fillna(x.median())
    )
print(f"Nulos restantes en numéricas: {df[cols_numericas].isnull().sum().sum()}")

# Eliminar filas con nulos en el target y RainToday
df = df.dropna(subset=['RainToday', 'RainTomorrow']).reset_index(drop=True)
print(f"Filas tras limpieza del target: {df.shape[0]}")

"""El resultado de 57,617 nulos restantes resulta inesperado dado que se aplicó imputación por mediana. Para diagnosticar la causa, se investiga si alguna combinación estación-columna tiene todos sus valores en NaN, lo que explicaría por qué la mediana local no pudo imputar nada en esos casos."""

# Ver qué combinaciones Location-columna quedaron todas en NaN
cols_numericas = df.select_dtypes(include='float64').columns

problemas = []
for col in cols_numericas:
    for loc in df['Location'].unique():
        subset = df[df['Location'] == loc][col]
        if subset.isnull().all():
            problemas.append({'Location': loc, 'Columna': col, 'Nulos': subset.isnull().sum()})

pd.DataFrame(problemas).sort_values('Columna')

"""Al verificar los nulos restantes, se detecta que ciertas estaciones tienen columnas completamente vacías: `Cloud9am` y `Cloud3pm` en GoldCoast, Tuggeranong, Penrith, NorahHead, BadgerysCreek y MountGinini; `Pressure9am` y `Pressure3pm` en Newcastle, Penrith y MountGinini; y WindGustSpeed en Newcastle. En estos casos la mediana por estación también es NaN, por lo que la imputación anterior no tuvo efecto. Para resolverlo se aplica un segundo paso de imputación usando la mediana global como fallback."""

# Fallback: imputar con mediana global los nulos que quedaron
cols_numericas = df.select_dtypes(include='float64').columns

for col in cols_numericas:
    if df[col].isnull().sum() > 0:
        df[col] = df[col].fillna(df[col].median())

print(f"Nulos restantes tras fallback: {df[cols_numericas].isnull().sum().sum()}")

"""Las variables de dirección del viento (`WindGustDir`, `WindDir9am`, `WindDir3pm`) son categóricas nominales con 16 valores posibles correspondientes a los puntos cardinales. Se imputan con la moda por estación (`Location`), ya que la dirección predominante del viento varía según la geografía de cada región."""

cols_viento = ['WindGustDir', 'WindDir9am', 'WindDir3pm']

for col in cols_viento:
    df[col] = df.groupby('Location')[col].transform(
        lambda x: x.fillna(x.mode()[0]) if not x.mode().empty else x
    )

print("Nulos restantes en variables de viento:")
print(df[cols_viento].isnull().sum())

"""Se detecta que Newcastle no tiene ningún registro válido de `WindGustDir`, por lo que la moda local también es NaN. Se aplica un fallback con la moda global."""

# Fallback: moda global para WindGustDir
df['WindGustDir'] = df['WindGustDir'].fillna(df['WindGustDir'].mode()[0])

print("Nulos restantes en variables de viento:")
print(df[cols_viento].isnull().sum())

"""### Análisis de valores atípicos

Se analizan los rangos de las variables numéricas clave para detectar valores físicamente imposibles.
"""

cols_check = ['MinTemp', 'MaxTemp', 'Rainfall', 'WindGustSpeed',
              'Humidity9am', 'Humidity3pm', 'Pressure9am', 'Pressure3pm']

df[cols_check].describe()

"""Los rangos observados son físicamente plausibles para el contexto geográfico del dataset. La lluvia máxima de 371mm y ráfagas de hasta 135 km/h son valores extremos pero posibles en zonas tropicales como Queensland. Las temperaturas, humedad y presión se encuentran dentro de rangos válidos. No se eliminan registros por valores atípicos ya que, además, los modelos de árbol de decisión y random forest son inherentemente robustos frente a outliers al trabajar con particiones binarias en lugar de distancias.

### Análisis de la variable objetivo

#### Distribución de la variable objetivo
"""

target_counts = df['RainTomorrow'].value_counts()
target_pct = df['RainTomorrow'].value_counts(normalize=True) * 100

plt.figure(figsize=(6, 6))
bars = plt.bar(target_counts.index, target_counts.values, color=['steelblue', 'tomato'])
for bar, pct in zip(bars, target_pct.values):
    plt.text(bar.get_x() + bar.get_width() / 2, bar.get_height() + 100,
             f'{pct:.1f}%', ha='center', va='bottom', fontsize=12, fontweight='bold')
plt.title('Distribución de la variable objetivo: RainTomorrow')
plt.ylabel('Cantidad de registros')
plt.xlabel('RainTomorrow')
plt.tight_layout()
plt.show()

print(f"No llueve: {target_counts['No']} ({target_pct['No']:.1f}%)")
print(f"Llueve:    {target_counts['Yes']} ({target_pct['Yes']:.1f}%)")

"""El dataset está claramente desbalanceado: aproximadamente el 78% de los días no llueve y solo el 22% sí llueve. Este desbalance debe tenerse en cuenta al entrenar los modelos (uso de `class_weight='balanced'` y `scale_pos_weight`) y al elegir la métrica de evaluación (se prioriza recall sobre accuracy).

#### Matriz de correlacion entre variables continuas
"""

cols_corr = ['MinTemp', 'MaxTemp', 'Rainfall', 'WindGustSpeed',
             'Humidity9am', 'Humidity3pm', 'Pressure9am', 'Pressure3pm',
             'Cloud9am', 'Cloud3pm', 'Temp9am', 'Temp3pm']

corr_matrix = df[cols_corr].corr()

plt.figure(figsize=(12, 9))
sns.heatmap(corr_matrix, annot=True, fmt='.2f', cmap='coolwarm', center=0,
            linewidths=0.5, annot_kws={'size': 8})
plt.title('Matriz de correlación — Variables meteorológicas continuas')
plt.tight_layout()
plt.show()

"""#### Boxplots: variables clave según RainTomorrow"""

vars_boxplot = ['Humidity3pm', 'Humidity9am', 'Pressure3pm', 'WindGustSpeed', 'Rainfall', 'Cloud3pm']

fig, axes = plt.subplots(2, 3, figsize=(14, 8))
axes = axes.flatten()

for i, var in enumerate(vars_boxplot):
    sns.boxplot(
        x='RainTomorrow',
        y=var,
        data=df,
        ax=axes[i],
        hue='RainTomorrow',
        palette={'No': 'steelblue', 'Yes': 'tomato'},
        legend=False
    )
    axes[i].set_title(f'{var} según RainTomorrow')
    axes[i].set_xlabel('RainTomorrow')
    axes[i].set_ylabel(var)

plt.suptitle('Distribución de variables clave por clase objetivo', fontsize=13, fontweight='bold', y=1.01)
plt.tight_layout()
plt.show()

"""### Feature Engineering

Se crean nuevas variables que pueden aportar señal predictiva al modelo.
"""

# Variables temporales
df['Month'] = df['Date'].dt.month
df['Season'] = df['Month'].map({
    12: 'Verano', 1: 'Verano', 2: 'Verano',
    3: 'Otoño',  4: 'Otoño',  5: 'Otoño',
    6: 'Invierno', 7: 'Invierno', 8: 'Invierno',
    9: 'Primavera', 10: 'Primavera', 11: 'Primavera'
})

# Rango térmico diario
df['TempRange'] = df['MaxTemp'] - df['MinTemp']

# Caída de humedad entre mañana y tarde
df['HumidityDrop'] = df['Humidity9am'] - df['Humidity3pm']

# Caída de presión entre mañana y tarde (presión cayendo = posible lluvia)
df['PressureDrop'] = df['Pressure9am'] - df['Pressure3pm']

df[['TempRange', 'HumidityDrop', 'PressureDrop', 'Month', 'Season']].describe()

"""### Encoding y preparación para los modelos"""

# Encoding binario de RainToday y RainTomorrow
df['RainToday_enc'] = (df['RainToday'] == 'Yes').astype(int)
df['RainTomorrow_enc'] = (df['RainTomorrow'] == 'Yes').astype(int)

# Label Encoding para direcciones de viento y variables categóricas
le = LabelEncoder()
for col in ['WindGustDir', 'WindDir9am', 'WindDir3pm', 'Location', 'Season']:
    df[col + '_enc'] = le.fit_transform(df[col].astype(str))

# Definir features y target
features = ['MinTemp', 'MaxTemp', 'Rainfall', 'WindGustSpeed',
            'WindSpeed9am', 'WindSpeed3pm', 'Humidity9am', 'Humidity3pm',
            'Pressure9am', 'Pressure3pm', 'Cloud9am', 'Cloud3pm',
            'Temp9am', 'Temp3pm', 'TempRange', 'HumidityDrop', 'PressureDrop',
            'RainToday_enc', 'WindGustDir_enc', 'WindDir9am_enc', 'WindDir3pm_enc',
            'Location_enc', 'Season_enc', 'Month']

X = df[features]
y = df['RainTomorrow_enc']

print(f"\nShape X: {X.shape}")
print(f"\nDistribución target:")
print(y.value_counts())
print(f"\nDesbalance: {y.value_counts(normalize=True).round(3) * 100}")

"""### Normalización de variables

Si bien los modelos de Árbol de decisión y Random Forest son invariantes a la escala de las variables, se realiza una estandarización (StandardScaler) sobre las variables numéricas continuas como paso de preprocesamiento general. Esto se debe a que el Modelo 3 a elección puede requerir que las features estén en una escala comparable. Las variables categóricas codificadas (direcciones de viento, ubicación, estación) y las binarias (RainToday_enc) no se escalan ya que su codificación numérica no representa magnitud.

## 2. Entrenamiento y predicción (80% train / 20% test)
"""

# Split 80/20
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

# Normalización DESPUÉS del split para evitar data leakage
scaler = StandardScaler()

cols_escalar = ['MinTemp', 'MaxTemp', 'Rainfall', 'WindGustSpeed',
                'WindSpeed9am', 'WindSpeed3pm', 'Humidity9am', 'Humidity3pm',
                'Pressure9am', 'Pressure3pm', 'Cloud9am', 'Cloud3pm',
                'Temp9am', 'Temp3pm', 'TempRange', 'HumidityDrop', 'PressureDrop']

scaler.fit(X_train[cols_escalar])

X_train_scaled = X_train.copy()
X_train_scaled[cols_escalar] = scaler.transform(X_train[cols_escalar])

X_test_scaled = X_test.copy()
X_test_scaled[cols_escalar] = scaler.transform(X_test[cols_escalar])

# Nota: los modelos de árbol (Árbol de decisión, Random Forest, XGBoost) son invariantes
# al escalado, por lo que se entrenan con X_train sin escalar. El scaler se guarda en el
# pkl por consistencia, en caso de que se incorpore un modelo lineal futuro.

print(f"X_train: {X_train.shape} | X_test: {X_test.shape}")
print(f"y_train dist: {y_train.value_counts(normalize=True).round(3).to_dict()}")
print(f"Scaler ajustado sobre {len(cols_escalar)} columnas")

"""### Modelo 1 – Árbol de decisión"""

# Modelo inicial
tree_model = tree.DecisionTreeClassifier(criterion='entropy', max_depth=10, min_samples_leaf=10)
model = tree_model.fit(X=X_train, y=y_train)

# Predicción
y_pred = model.predict(X_test)

# Métricas
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Recall:", recall_score(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred))
print("F1 score:", f1_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

# Gráfico árbol reducido (legible)
plt.figure(figsize=(12, 12))
tree.plot_tree(model, max_depth=2, feature_names=X.columns.tolist(), filled=True, rounded=True, class_names=['No Rain', 'Rain'])
plt.title('Árbol de Decisión inicial (primeros 2 niveles)')
plt.show()

# Matriz de confusión
tabla = confusion_matrix(y_test, y_pred)
sns.heatmap(tabla, cmap='Blues', annot=True, fmt='g')
plt.xlabel('Predicted')
plt.ylabel('True')
plt.title('Matriz de confusión - Árbol inicial')
plt.show()

# Importancia de atributos
importancias = sorted(zip(X.columns.tolist(), model.feature_importances_), key=lambda x: x[1], reverse=True)

df_importancias = pd.DataFrame(importancias, columns=['Variable', 'Importancia'])
df_importancias['Importancia'] = df_importancias['Importancia'].map('{:.4f}'.format)
print(df_importancias.to_string(index=False))

# Modelo con poda
tree_poda = tree.DecisionTreeClassifier(criterion='entropy', max_depth=10, min_samples_leaf=10, ccp_alpha=0.001)
model_poda = tree_poda.fit(X=X_train, y=y_train)
y_pred_poda = model_poda.predict(X_test)

print("Accuracy poda:", accuracy_score(y_test, y_pred_poda))
print("Recall poda:", recall_score(y_test, y_pred_poda))
print("Precision poda:", precision_score(y_test, y_pred_poda))
print("F1 score poda:", f1_score(y_test, y_pred_poda))

tabla_poda = confusion_matrix(y_test, y_pred_poda)
sns.heatmap(tabla_poda, cmap='Blues', annot=True, fmt='g')
plt.xlabel('Predicted')
plt.ylabel('True')
plt.title('Matriz de confusión - Árbol con poda')
plt.show()

"""#### Optimización de hiperparámetros

"""

param_grid = {
    'max_depth': [5, 10, 15, 20],
    'min_samples_leaf': [5, 10, 20],
    'ccp_alpha': [0.0, 0.001, 0.005, 0.01]
}

grid_search = GridSearchCV(
    tree.DecisionTreeClassifier(criterion='entropy', class_weight='balanced', random_state=42),
    param_grid,
    cv=5,
    scoring='f1',
    n_jobs=-1,
    verbose=1
)

grid_search.fit(X_train, y_train)

print("Mejores hiperparámetros:", grid_search.best_params_)
print("Mejor F1 en CV:", grid_search.best_score_)

# Modelo final con hiperparámetros optimizados
model_final = grid_search.best_estimator_

# Predicción
y_pred_final = model_final.predict(X_test)

# Métricas
print("Accuracy:", accuracy_score(y_test, y_pred_final))
print("Recall:", recall_score(y_test, y_pred_final))
print("Precision:", precision_score(y_test, y_pred_final))
print("F1 score:", f1_score(y_test, y_pred_final))
print(classification_report(y_test, y_pred_final))

# Matriz de confusión con hiperparámetros optimizados
tabla_final = confusion_matrix(y_test, y_pred_final)
sns.heatmap(tabla_final, cmap='Blues', annot=True, fmt='g')
plt.xlabel('Predicted')
plt.ylabel('True')
plt.title('Matriz de confusión - Árbol final (CV)')
plt.show()

# Evaluación en el conjunto de entrenamiento (para detectar overfitting)
y_train_pred_dt = model_final.predict(X_train)
print("=== Árbol de decisión — Performance en TRAIN ===")
print("Train — Accuracy: ", accuracy_score(y_train, y_train_pred_dt))
print("Train — Recall:   ", recall_score(y_train, y_train_pred_dt))
print("Train — Precision:", precision_score(y_train, y_train_pred_dt))
print("Train — F1:       ", f1_score(y_train, y_train_pred_dt))

# Gráfico árbol reducido (legible)
plt.figure(figsize=(14, 8))
tree.plot_tree(model_final, max_depth=2, feature_names=X.columns.tolist(), filled=True, rounded=True, class_names=['No Rain', 'Rain'])
plt.title('Árbol de Decisión final (primeros 2 niveles)')
plt.show()

"""#### Importancia de atributos

"""

df_plot = df_importancias.head(10).copy()
df_plot['Importancia'] = df_plot['Importancia'].astype(float)
df_plot = df_plot.sort_values('Importancia', ascending=True)

plt.figure(figsize=(10, 5))
sns.barplot(x='Variable', y='Importancia', data=df_plot, color='steelblue', order=df_plot['Variable'])
plt.title('Top 10 - Importancia de atributos (Árbol de decisión)')
plt.xlabel('Variable')
plt.ylabel('Importancia')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

"""#### Interpretación de reglas del árbol
El nodo raíz divide por Humidity3pm <= 66.5. Si la humedad a las 3pm es baja (≤ 66.5%), el árbol va por la rama izquierda (naranja, No llueve), y si es alta (> 66.5%) va por la derecha (azul, Llueve).

Rama izquierda (humedad baja, tiende a No llueve):

Si además Humidity3pm <= 51.5 y WindGustSpeed <= 45 → No llueve con alta confianza

Si Humidity3pm está entre 51.5 y 66.5, se evalúa Rainfall <= 0.55 para refinar

Rama derecha (humedad alta, tiende a Llueve):

Si Humidity3pm <= 82.5 se evalúa Rainfall <= 0.45 para decidir

Si Humidity3pm > 82.5 se evalúa Temp9am <= 8.05, temperaturas bajas con humedad muy alta indican lluvia casi segura

#### Evaluación de performance
El modelo final obtenido mediante GridSearchCV con validación cruzada de 5 folds alcanzó un accuracy de 0.8 y un recall de 0.8 para la clase lluvia. Dado el desbalance de clases presente en el dataset (78% No lluvia / 22% lluvia), se utilizó class_weight='balanced' para que el modelo no ignorara la clase minoritaria durante el entrenamiento. Como métrica principal se priorizó el recall: el modelo detecta correctamente 8 de cada 10 días de lluvia real. La precision de 0.53 indica que hay falsos positivos, pero en contexto meteorológico es preferible alertar de más que no detectar una lluvia real.

### Modelo 2 – Random Forest
"""

print("Proporción de clases en y_train:")
print(y_train.value_counts(normalize=True))

from sklearn.ensemble import RandomForestClassifier

# Modelo inicial
rf_inicial = RandomForestClassifier(
    n_estimators=100,
    criterion='entropy',
    max_depth=10,
    min_samples_leaf=10,
    random_state=42,
    n_jobs=-1
)

rf_inicial.fit(X_train, y_train)
y_pred_rf = rf_inicial.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred_rf))
print("Recall:",   recall_score(y_test, y_pred_rf))
print("Precision:",precision_score(y_test, y_pred_rf))
print("F1 Score:", f1_score(y_test, y_pred_rf))
print(classification_report(y_test, y_pred_rf))

tabla_rf = confusion_matrix(y_test, y_pred_rf)
sns.heatmap(tabla_rf, cmap='Blues', annot=True, fmt='g')
plt.xlabel('Predicted')
plt.ylabel('True')
plt.title('Matriz de confusión - Random Forest inicial')
plt.show()

"""#### Optimización de hiperparámetros"""

from sklearn.model_selection import StratifiedKFold, RandomizedSearchCV
from sklearn.metrics import make_scorer, recall_score
from sklearn.ensemble import RandomForestClassifier

params_rf = {
    'n_estimators': [100],
    'max_depth': [10, 15, 20, None],
    'min_samples_split': [2, 5],
    'min_samples_leaf': [1, 2],
    'max_features': ['sqrt'],
    'criterion': ['entropy'],
    'class_weight': ['balanced']
}

kfoldcv = StratifiedKFold(n_splits=3, shuffle=True, random_state=42)

rf_search = RandomizedSearchCV(
    estimator=RandomForestClassifier(random_state=42, n_jobs=-1),
    param_distributions=params_rf,
    scoring=make_scorer(recall_score),
    cv=kfoldcv,
    n_iter=8,
    random_state=42,
    n_jobs=-1
)

rf_search.fit(X_train, y_train)
print("Mejores hiperparámetros:", rf_search.best_params_)
print(f"Mejor Recall (CV): {rf_search.best_score_:.4f}")

rf_final = RandomForestClassifier(
    **rf_search.best_params_,
    random_state=42,
    n_jobs=-1
)
rf_final.fit(X_train, y_train)

y_pred_rf_final = rf_final.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred_rf_final))
print("Recall:", recall_score(y_test, y_pred_rf_final))
print("Precision:", precision_score(y_test, y_pred_rf_final))
print("F1 Score:", f1_score(y_test, y_pred_rf_final))
print(classification_report(y_test, y_pred_rf_final))

# Evaluación en el conjunto de entrenamiento (para detectar overfitting)
y_train_pred_rf = rf_final.predict(X_train)
print("=== Random Forest — Performance en TRAIN ===")
print("Train — Accuracy: ", accuracy_score(y_train, y_train_pred_rf))
print("Train — Recall:   ", recall_score(y_train, y_train_pred_rf))
print("Train — Precision:", precision_score(y_train, y_train_pred_rf))
print("Train — F1:       ", f1_score(y_train, y_train_pred_rf))

tabla_rf_final = confusion_matrix(y_test, y_pred_rf_final)
sns.heatmap(tabla_rf_final, cmap='Blues', annot=True, fmt='g')
plt.xlabel('Predicted')
plt.ylabel('True')
plt.title('Matriz de confusión - Random Forest optimizado')
plt.show()

"""#### Importancia de atributos

El Random Forest distribuye la importancia entre más variables que el árbol individual, ya que cada árbol del bosque considera subconjuntos aleatorios de features en cada split. Esto reduce el efecto dominante de una única variable y permite identificar señales predictivas más distribuidas.
"""

importancias_rf = pd.Series(
    rf_final.feature_importances_,
    index=X.columns
).sort_values(ascending=False).head(10)

plt.figure(figsize=(10, 5))
sns.barplot(x=importancias_rf.values, y=importancias_rf.index, color='steelblue')
plt.title('Top 10 - Importancia de atributos (Random Forest)')
plt.xlabel('Importancia')
plt.ylabel('Variable')
plt.tight_layout()
plt.show()

print(importancias_rf)

"""La variable más importante sigue siendo `Humidity3pm` (21%), pero su peso es mucho menor que en el árbol individual donde dominaba con 55%. Esto es una característica clave del Random Forest: al considerar subconjuntos aleatorios de features en cada split, evita que una sola variable monopolice las decisiones.
También aparecen variables de feature engineering creadas en el preprocesamiento: `TempRange` (rango térmico diario) y `HumidityDrop` (caída de humedad entre mañana y tarde) con 7% cada una, lo que valida que esas variables aportan información predictiva real. `RainToday_enc` aparece con 5%, a diferencia del árbol individual donde tenía importancia 0, lo que sugiere que el RF aprovecha mejor señales débiles.

A diferencia del árbol de decisión individual, el Random Forest no tiene un único árbol interpretable. Sin embargo, es posible visualizar uno de los árboles que lo componen para ilustrar cómo cada árbol individual toma decisiones con un subconjunto aleatorio de variables.
"""

arbol_rep = rf_final.estimators_[0]

plt.figure(figsize=(14, 8))
tree.plot_tree(
    arbol_rep,
    max_depth     = 2,
    feature_names = X.columns.tolist(),
    filled        = True,
    rounded       = True,
    class_names   = ['No Rain', 'Rain'],
    fontsize      = 10
)
plt.title('Árbol representativo del Random Forest (primeros 2 niveles)')
plt.tight_layout()
plt.show()

"""#### Interpretación del árbol representativo del Random Forest
A diferencia del árbol de decisión individual donde el nodo raíz era `Humidity3pm`, este árbol del bosque divide primero por `Rainfall <= 0.35`, lo cual refleja que al considerar solo un subconjunto aleatorio de features en cada split, cada árbol puede encontrar variables distintas como punto de partida.

**Rama izquierda (Rainfall ≤ 0.35 → lluvia escasa, tiende a No Rain):**
Con 22.339 muestras, el nodo evalúa `Pressure9am <= 1018.05`. Una presión baja en la mañana es indicador meteorológico clásico de inestabilidad atmosférica. Si la presión es baja Y la humedad a las 3pm es alta (> 67.5), aumenta la probabilidad de lluvia. Si la presión es baja pero la caída de humedad es pequeña (`HumidityDrop <= 6.5`), el modelo tiende a predecir No Rain igualmente.

**Rama derecha (Rainfall > 0.35 → ya llovió algo, tiende a Rain):**
Con solo 9.036 muestras pero mayoría clase Rain, subdivide por `Cloud9am <= 4.25`. Si hay poca nubosidad matutina a pesar de la lluvia, evalúa `MaxTemp <= 25.85`. Si hay mucha nube y además `Humidity9am > 78.5`, el modelo predice lluvia con bastante confianza.

La diferencia clave con el árbol del Modelo 1 es que aquí no aparece `Humidity3pm` como nodo raíz, aunque sí aparece en niveles inferiores. Esto ilustra el mecanismo central del Random Forest: al forzar subconjuntos aleatorios de variables, los árboles se decorrelacionan entre sí, lo que reduce la varianza del ensamble.

### Modelo 3 – XGBoost

Como tercer modelo se elige XGBoost (Extreme Gradient Boosting), una implementación optimizada del algoritmo de Gradient Boosting que construye árboles de decisión de forma secuencial, donde cada árbol nuevo se entrena para corregir los errores del anterior minimizando una función de pérdida mediante descenso por gradiente.

XGBoost construye árboles en secuencia priorizando los ejemplos mal clasificados, lo que en la práctica genera un mejor trade-off sesgo-varianza y suele traducirse en mayor precisión predictiva.
Por otro lado, los tres modelos representan familias distintas (árbol individual → bagging → boosting), lo que permitirá una comparación significativa en el cuadro final.

Además, XGBoost reduce el riesgo de overfitting respecto al Gradient Boosting clásico, y es naturalmente robusto frente a outliers sin requerir que las features estén normalizadas.

Por último, XGBoost ofrece el parámetro scale_pos_weight, que permite compensar explícitamente el desbalance de clases penalizando más los errores sobre la clase minoritaria durante el entrenamiento. Esto es especialmente relevante en este problema donde solo el 22% de los registros corresponden a días de lluvia, y donde el recall es la métrica prioritaria de evaluación.
"""

from xgboost import XGBClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import accuracy_score, recall_score, precision_score, f1_score, classification_report, confusion_matrix

# Modelo inicial
neg, pos = (y_train == 0).sum(), (y_train == 1).sum()

xgb_inicial = XGBClassifier(
    random_state=42,
    eval_metric='logloss',
    n_jobs=-1
)
xgb_inicial.fit(X_train, y_train)
y_pred_xgb = xgb_inicial.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred_xgb))
print("Recall:", recall_score(y_test, y_pred_xgb))
print("Precision:", precision_score(y_test, y_pred_xgb))
print("F1 Score:", f1_score(y_test, y_pred_xgb))
print(classification_report(y_test, y_pred_xgb))

# Matriz de confusión inicial
tabla_xgb = confusion_matrix(y_test, y_pred_xgb)
sns.heatmap(tabla_xgb, cmap='Blues', annot=True, fmt='g')
plt.xlabel('Predicted')
plt.ylabel('True')
plt.title('Matriz de confusión - XGBoost inicial')
plt.show()

"""#### Optimización de hiperparámetros"""

param_grid_xgb = {
    'max_depth': [3, 5],
    'learning_rate': [0.05, 0.1],
    'n_estimators': [100, 200],
}

grid_xgb = GridSearchCV(
    XGBClassifier(
        scale_pos_weight=neg/pos,
        random_state=42,
        eval_metric='logloss',
        n_jobs=-1
    ),
    param_grid_xgb,
    cv=3,
    scoring='f1',
    n_jobs=-1,
    verbose=1
)
grid_xgb.fit(X_train, y_train)

print("Mejores hiperparámetros:", grid_xgb.best_params_)
print("Mejor F1 en CV:", grid_xgb.best_score_)

xgb_final = grid_xgb.best_estimator_
y_pred_xgb_final = xgb_final.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred_xgb_final))
print("Recall:", recall_score(y_test, y_pred_xgb_final))
print("Precision:", precision_score(y_test, y_pred_xgb_final))
print("F1 Score:", f1_score(y_test, y_pred_xgb_final))
print(classification_report(y_test, y_pred_xgb_final))

# Evaluación en el conjunto de entrenamiento (para detectar overfitting)
y_train_pred_xgb = xgb_final.predict(X_train)
print("=== XGBoost — Performance en TRAIN ===")
print("Train — Accuracy: ", accuracy_score(y_train, y_train_pred_xgb))
print("Train — Recall:   ", recall_score(y_train, y_train_pred_xgb))
print("Train — Precision:", precision_score(y_train, y_train_pred_xgb))
print("Train — F1:       ", f1_score(y_train, y_train_pred_xgb))

"""El modelo inicial se entrena sin corrección de desbalance para observar el comportamiento base del algoritmo. Como era de esperarse, el modelo obtiene un recall de 0.55 para la clase minoritaria (lluvia), evidenciando que tiende a predecir mayormente "No llueve" para maximizar el accuracy, ignorando una proporción significativa de los días de lluvia real.
Por este motivo, se incorpora scale_pos_weight=neg/pos como hiperparámetro clave en la optimización de XgBoost. Este parámetro calcula la proporción entre ejemplos negativos y positivos (≈ 3.5), indicándole al modelo que cada error sobre la clase minoritaria debe penalizarse 3.5 veces más que un error sobre la clase mayoritaria. Es el equivalente directo de class_weight='balanced' utilizado en árboles de decisión y Random Forest.
"""

# Matriz de confusión final
tabla_xgb_final = confusion_matrix(y_test, y_pred_xgb_final)
sns.heatmap(tabla_xgb_final, cmap='Blues', annot=True, fmt='g')
plt.xlabel('Predicted')
plt.ylabel('True')
plt.title('Matriz de confusión - XGBoost optimizado')
plt.show()

"""#### Importancia de atributos"""

importancias_xgb = pd.Series(
    xgb_final.feature_importances_,
    index=X.columns
).sort_values(ascending=False).head(10)

plt.figure(figsize=(10, 5))
sns.barplot(x=importancias_xgb.values, y=importancias_xgb.index, color='steelblue')
plt.title('Top 10 - Importancia de atributos (XGBoost)')
plt.xlabel('Importancia')
plt.ylabel('Variable')
plt.tight_layout()
plt.show()

print(importancias_xgb)

"""## 3. Comparación de modelos"""

# Cuadro comparativo de modelos
modelos = ['Árbol de decisión', 'Random Forest', 'XGBoost']
metricas = {
    'Accuracy':  [accuracy_score(y_test, y_pred_final),
                  accuracy_score(y_test, y_pred_rf_final),
                  accuracy_score(y_test, y_pred_xgb_final)],
    'Recall':    [recall_score(y_test, y_pred_final),
                  recall_score(y_test, y_pred_rf_final),
                  recall_score(y_test, y_pred_xgb_final)],
    'Precision': [precision_score(y_test, y_pred_final),
                  precision_score(y_test, y_pred_rf_final),
                  precision_score(y_test, y_pred_xgb_final)],
    'F1':        [f1_score(y_test, y_pred_final),
                  f1_score(y_test, y_pred_rf_final),
                  f1_score(y_test, y_pred_xgb_final)],
}

df_comp = pd.DataFrame(metricas, index=modelos)

fig, ax = plt.subplots(figsize=(10, 4))
ax.axis('off')

tabla = ax.table(
    cellText=df_comp.values.round(2),
    rowLabels=df_comp.index,
    colLabels=df_comp.columns,
    cellLoc='center',
    loc='center'
)

tabla.auto_set_font_size(False)
tabla.set_fontsize(12)
tabla.scale(1.4, 2)

# Colores de encabezado y filas
for (row, col), cell in tabla.get_celld().items():
    if row == 0:
        cell.set_facecolor('#2c7bb6')
        cell.set_text_props(color='white', fontweight='bold')
    elif col == -1:
        cell.set_facecolor('#d9e8f5')
        cell.set_text_props(fontweight='bold')
    elif row % 2 == 0:
        cell.set_facecolor('#f0f7ff')
    else:
        cell.set_facecolor('white')

# Resaltar mejor valor por columna
for col_idx, col_name in enumerate(df_comp.columns):
    mejor_fila = df_comp[col_name].idxmax()
    mejor_row = df_comp.index.get_loc(mejor_fila) + 1
    tabla[mejor_row, col_idx].set_facecolor('#d4edda')
    tabla[mejor_row, col_idx].set_text_props(fontweight='bold')

plt.title('Comparación de modelos de clasificación', fontsize=14, fontweight='bold', pad=20)
plt.tight_layout()
plt.show()

"""Se elige XGBoost como modelo final. Es el que mejor desempeño obtiene en las métricas prioritarias para este problema: mayor recall (0.75) y mayor F1 (0.65), manteniendo una accuracy y precisión similares al Random Forest.
Dado el desbalance de clases presente en el dataset (78% No lluvia / 22% lluvia) y el contexto meteorológico, el recall es la métrica más relevante: es más costoso no detectar un día de lluvia real que generar una falsa alarma. XGBoost logra detectar correctamente 3 de cada 4 días de lluvia real, superando al árbol de decisión (0.71) y al Random Forest (0.69), siendo por tanto el modelo más adecuado para este problema.

## Guardado de modelos y dataset procesado
"""

import joblib
import os

# Scaler (necesario para reproducir predicciones con Modelo 3)
joblib.dump(scaler, "TA047R_TP1_GRUPO02_EJ2_scaler.pkl")

# Modelo 1 — Árbol de decisión (optimizado con GridSearchCV)
joblib.dump(model_final, "TA047R_TP1_GRUPO02_EJ2_modelo_arbol_decision.pkl")

# Modelo 2 — Random Forest (optimizado con RandomizedSearchCV)
joblib.dump(rf_final, "TA047R_TP1_GRUPO02_EJ2_modelo_random_forest.pkl")

# Modelo 3 — XGBoost (optimizado con GridSearchCV)
joblib.dump(xgb_final, "TA047R_TP1_GRUPO02_EJ2_modelo_xgboost.pkl")

# Verificación
archivos = [
    "TA047R_TP1_GRUPO02_EJ2_scaler.pkl",
    "TA047R_TP1_GRUPO02_EJ2_modelo_arbol_decision.pkl",
    "TA047R_TP1_GRUPO02_EJ2_modelo_random_forest.pkl",
    "TA047R_TP1_GRUPO02_EJ2_modelo_xgboost.pkl",
]
print("Archivos guardados:")
for f in archivos:
    size = os.path.getsize(f) / 1024
    print(f"  {f}  →  {size:.1f} KB")

nombre_dataset = "TA047R_TP1_GRUPO02_EJ2_weather_australia_procesado.csv"
df.to_csv(nombre_dataset, index=False)

size_kb = os.path.getsize(nombre_dataset) / 1024
print(f"Dataset guardado: {nombre_dataset}")
print(f"Tamaño: {size_kb:.1f} KB")
print(f"Shape: {df.shape}")