# -*- coding: utf-8 -*-
"""TA047R_TP1_GRUPO02_ENTREGA_EJ3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wAcRWi1yj5OCwA1C6iY2lQVsnzI2vUVb

# Trabajo Práctico 1 - Grupo 02

### Ejercicio 3

Integrantes:

*   Bermudez, Agustin
*   Calderón, Tiago
*   Gonzalez Pautaso, Mateo
*   Moreyra, Santiago
*   Nieves, Maylen

## Carga de los datos e inspección inicial
"""

import pandas as pd
import numpy as np
import seaborn as sns
import sklearn as sk
import matplotlib.pyplot as plt

df = pd.read_csv('https://data.insideairbnb.com/italy/lombardy/milan/2025-09-22/data/listings.csv.gz')

filas, columnas = df.shape
print(f" --- Dimensiones del dataset: {filas} filas × {columnas} columnas ---\n")

df.head()

# Analizamos los tipos de cada variable
df.info()

# Porcentaje de nulos por columna
nulls = (df.isna().sum() / len(df) * 100).round(2)
nulls = nulls[nulls > 0].sort_values(ascending=False)
print(nulls.to_string())

# Estadisticas basicas
df.describe()

# Cantidad de valores unicos que toma cada variable
print(df.nunique().to_string())

"""## Preparación de la variable target

Como la variable `price` será el objetivo a predecir, vamos a hacer una preparación especial de la misma.

Empezando por ver algunos valores del dataframe
"""

df['price'].head(10)

"""### Tratamiento del tipo de dato

Como se puede ver, esta variable viene con un formato de `string`, por lo que lo primero que vamos a hacer el pasarla al tipo de dato correcto `float`, ya que es una variable cuantitativa continua.
"""

df['price'] = df['price'].str.replace('$', '', regex=False)
df['price'] = df['price'].str.replace(',', '', regex=False)
df['price'] = df['price'].astype(float)
df['price'].head(10)

"""### Tratamiento de los nulos"""

### Cantidad de nulos
nulos_price = df['price'].isna().sum()
print(f"Cantidad de valores nulos de la variable 'price': {int(nulos_price)}")

"""Al ser la varaible target, no vamos a imputar los valores faltantes. Directamente eliminamos las filas cuyo `price` es nulo"""

df = df.dropna(subset=['price'])
nulos_price = df['price'].isna().sum()
print(f"Cantidad de valores nulos de la variable 'price' despues de eliminar los nulos: {int(nulos_price)}")

"""### Creación de `price_log`"""

fig, ax = plt.subplots(figsize=(8, 4))

ax.hist(df['price'], bins=80, color='steelblue', edgecolor='black')
ax.set_title(f'Distribución de price (n={len(df):,})')
ax.set_xlabel('price')
ax.set_ylabel('Frecuencia')
ax.axvline(df['price'].median(), color='black', linestyle='--', label=f'Mediana: {df["price"].median():.0f}')
ax.axvline(df['price'].mean(), color='red', linestyle='--', label=f'Media: {df["price"].mean():.0f}')
ax.legend()

plt.tight_layout()
plt.show()

"""La variable `price` presenta una distribución fuertemente sesgada a la derecha, algunos valores extremadamente elevados provocan una distorsión en los gráficos de la distribuicón que se aprecia con todos los valores aplastados en una unica barra cerca del 0.

Aplicar una transformación logaritmica reduce el sesgo, acercando la distribución a una normal, mejorando el ajuste de modelos lineales y el filtrado de outliers reales.
"""

df['price_log'] = np.log1p(df['price'])

"""### Tratamiento de los outliers

Primero visualizamos la distribución actual de `price` y `price_log`
"""

fig, axes = plt.subplots(1, 2, figsize=(14, 4))

axes[0].hist(df['price'], bins=80, color='steelblue', edgecolor='black')
axes[0].set_title(f'Distribución de price (n={len(df):,})')
axes[0].set_xlabel('price')
axes[0].set_ylabel('Frecuencia')
axes[0].axvline(df['price'].median(), color='black', linestyle='--', label=f'Mediana: {df["price"].median():.0f}')
axes[0].axvline(df['price'].mean(), color='red', linestyle='--', label=f'Media: {df["price"].mean():.0f}')
axes[0].legend()

axes[1].hist(df['price_log'], bins=80, color='steelblue', edgecolor='black')
axes[1].set_title(f'Distribución de price_log (n={len(df):,})')
axes[1].set_xlabel('log(price + 1)')
axes[1].set_ylabel('Frecuencia')
axes[1].axvline(df['price_log'].median(), color='black', linestyle='--', label=f'Mediana: {df["price_log"].median():.2f}')
axes[1].axvline(df['price_log'].mean(), color='red', linestyle='--', label=f'Media: {df["price_log"].mean():.2f}')
axes[1].legend()

plt.suptitle('Distribución de price y price_log antes de filtrar')
plt.tight_layout()
plt.show()

"""Como método para eliminar las filas con valores atípicos de `price`, optamos por usar Z-score modificado sobre la variable `price_log`, esto porque el calculo del Z-score va a ser más preciso si se hace sobre una distribución mas simetrica. El objetivo es eliminar a las filas que puedan llegar a representar errores de carga, no a las propiedades que pueden contener información real pero dificil de encontrar."""

price_log = df['price_log']

median_global = price_log.median()
mad_global = (price_log - median_global).abs().median()
zscore = 0.6745 * (price_log - median_global) / mad_global
mask_zscore = zscore.abs() <= 3.5

filas_pre = len(df)
df = df[mask_zscore]
print(f"Filas antes del Z-score: {filas_pre:,}")
print(f"Filas después del Z-score: {len(df):,}")
print(f"Filas eliminadas: {filas_pre - len(df):,} ({(filas_pre - len(df)) / filas_pre * 100:.2f}%)")

"""Ahora visualizamos ambas distribuciones nuevamente, ya habiendo aplicado el filtro a los valores outliers"""

fig, axes = plt.subplots(1, 2, figsize=(14, 4))

axes[0].hist(df['price'], bins=80, color='steelblue', edgecolor='black')
axes[0].set_title(f'Distribución de price (n={len(df):,})')
axes[0].set_xlabel('price')
axes[0].set_ylabel('Frecuencia')
axes[0].axvline(df['price'].median(), color='black', linestyle='--', label=f'Mediana: {df["price"].median():.0f}')
axes[0].axvline(df['price'].mean(), color='red', linestyle='--', label=f'Media: {df["price"].mean():.0f}')
axes[0].legend()

axes[1].hist(df['price_log'], bins=80, color='steelblue', edgecolor='black')
axes[1].set_title(f'Distribución de price_log (n={len(df):,})')
axes[1].set_xlabel('log(price + 1)')
axes[1].set_ylabel('Frecuencia')
axes[1].axvline(df['price_log'].median(), color='black', linestyle='--', label=f'Mediana: {df["price_log"].median():.2f}')
axes[1].axvline(df['price_log'].mean(), color='red', linestyle='--', label=f'Media: {df["price_log"].mean():.2f}')
axes[1].legend()

plt.suptitle('Distribución de price y price_log después de filtrar')
plt.tight_layout()
plt.show()

"""## Filtrado de columnas irrelevantes

Antes de explorar los datos, eliminamos las columnas que no aportan información útil para predecir  `price`: identificadores, URLs, texto libre no procesable y columnas completamente vacías.

### Filtrado de las variables URLs

Las eliminamos porque solo son links a recursos externos y no aportan información relevante
"""

url_cols = ['listing_url', 'picture_url', 'host_url', 'host_thumbnail_url', 'host_picture_url']
df = df.drop(columns=url_cols)

"""### IDs y columnas del scraper

Eliminamos los identificadores y columnas técnicas generadas por el scraper, ya que no representan características del alojamiento sino metadatos del proceso de recolección de datos.
"""

scraping_cols = ['id', 'host_id', 'scrape_id', 'last_scraped', 'source', 'calendar_last_scraped']
df = df.drop(columns=scraping_cols)

"""### Texto libre

Eliminamos las columnas de texto libre ya que procesarlas correctamente queda fuera del alcance de este trabajo.
"""

text_cols = ['name', 'description', 'neighborhood_overview', 'host_about', 'host_name']
df = df.drop(columns=text_cols)

"""### Columnas completamente vacías

Eliminamos las columnas que no contienen ningún valor, ya que no aportan ninguna información.
"""

empty_cols = ['neighbourhood_group_cleansed', 'calendar_updated']
df = df.drop(columns=empty_cols)

"""### Variables redundantes

Eliminamos `neighbourhood` ya que viene vacía o contiene únicamente el valor genérico  "Milan, Lombardy, Italy", mientras que `neighbourhood_cleansed` provee el barrio específico de cada listing.

Eliminamos `host_neighbourhood` (67.75% de nulos) y `host_location` (20.84% de nulos) ya que ambas describen características del anfitrión y no de la propiedad. Para la predicción del precio, la ubicación relevante es la del alojamiento, disponible en `neighbourhood_cleansed` y en las coordenadas `latitude`/`longitude`.

Tambien se elimina `bathrooms_text` porque es la version sin procesar de `bathrooms`, que ya guarda esa información.
"""

df = df.drop(columns=['neighbourhood', 'bathrooms_text', 'host_neighbourhood', 'host_location'])

"""Verificamos si las distintas ventanas de disponibilidad (`availability_30`, `availability_60`, `availability_90`) aportan información adicional respecto a `availability_365`."""

def plot_correlation_heatmap(df, cols, titulo='Correlación entre variables'):
    sns.heatmap(
        df[cols].corr(),
        annot=True,
        fmt='.2f',
        cmap='coolwarm'
    )
    plt.title(titulo)
    plt.show()

availability_cols = ['availability_30', 'availability_60', 'availability_90', 'availability_365', 'availability_eoy']
plot_correlation_heatmap(df, availability_cols, 'Correlación entre variables de disponibilidad')

"""Las variables `availability_30`, `availability_60`, `availability_90` y `availability_eoy` están fuertemente correlacionadas entre sí (0.80-0.99), por lo que son redundantes. Conservamos `availability_30` como representante del corto plazo. `availability_365` al no tener una correlación suficiente (correlación de 0.35-0.47) optamos por conservarla."""

df = df.drop(columns=['availability_60', 'availability_90', 'availability_eoy'])

"""El dataset contiene múltiples variables relacionadas con las restricciones de noches mínimas y máximas. Analizamos su correlación para identificar redundancias y quedarnos con las más representativas."""

cols_nights = [
    'minimum_nights', 'maximum_nights',
    'minimum_minimum_nights', 'maximum_minimum_nights',
    'minimum_maximum_nights', 'maximum_maximum_nights',
    'minimum_nights_avg_ntm', 'maximum_nights_avg_ntm'
]

plot_correlation_heatmap(df, cols_nights, 'Correlación entre variables de noches')

"""El heatmap muestra dos grupos de alta correlación interna:

- `minimum_nights`, `minimum_minimum_nights`, `maximum_minimum_nights` y `minimum_nights_avg_ntm` (0.84-0.94)
- `minimum_maximum_nights`, `maximum_maximum_nights` y `maximum_nights_avg_ntm` (0.84-0.95)

De cada grupo conservamos un representante: `minimum_nights` y `maximum_nights` como foto actual del listing, y `minimum_nights_avg_ntm` y `maximum_nights_avg_ntm` como representantes del comportamiento futuro del calendario. El resto se elimina por redundante.
"""

redundant_nights = [
    'minimum_minimum_nights', 'maximum_minimum_nights',
    'minimum_maximum_nights', 'maximum_maximum_nights'
]
df = df.drop(columns=redundant_nights)

"""Hacemos un estudio de la variable `license` para saber que compartamiento tiene"""

print(df['license'].value_counts().head(20))
print(f"\nValores únicos: {df['license'].nunique()}")
print(f"Nulos: {df['license'].isna().sum()}")

"""Si bien `license` tiene 15.164 valores únicos y no es directamente utilizable como feature porque no podemos parsear el texto libre, contiene información útil: si un host tiene una licencia oficial podría correlacionarse con un perfil más profesional y por ende con el precio. Creamos una variable binaria `has_license` que preserva esta información antes de descartar la columna original.

Los valores nulos serán considerados como que no tienen licencia
"""

df['has_license'] = (
    df['license'].notna() &
    (df['license'] != 'Exempt') &
    (~df['license'].str.startswith('I applied', na=False))
)
df = df.drop(columns=['license'])
df['has_license'] = df['has_license'].astype(bool)

print(df['has_license'].value_counts())

"""### Análisis la variable `estimated_revenue_l365d`

Como el revenue estimado se calcula usando el precio, incluirla en el modelo sería darle información que deriva del target, causando un Data Leakeage
"""

df = df.drop(columns=['estimated_revenue_l365d'])

"""### Análisis de la cantidad de listings

Como existen muchas varbiales que se refieren a la cantidad de listados de propiedad que tiene el host, tomamos la decision de que necesitaban este apartado para estudiarlas y solo mantener la información relevante.

Segun el diccionario de data que provee **AirBnB**, las columnas `calculated_host_listings_count_entire_homes`, `calculated_host_listings_count_private_rooms`, `calculated_host_listings_count_shared_rooms` deberian sumar a `calculated_host_listings_count`. Lo primero que vamos a verificar es la consistencia de esa información.
"""

df['subtypes_sum'] = (
    df['calculated_host_listings_count_entire_homes'] +
    df['calculated_host_listings_count_private_rooms'] +
    df['calculated_host_listings_count_shared_rooms']
)
print((df['subtypes_sum'] == df['calculated_host_listings_count']).value_counts())
df = df.drop(columns=['subtypes_sum'])

"""Graficamos un heatmap para ver las correlaciones que tienen las variables entre sí."""

host_cols = [
    'host_listings_count',
    'host_total_listings_count',
    'calculated_host_listings_count',
    'calculated_host_listings_count_entire_homes',
    'calculated_host_listings_count_private_rooms',
    'calculated_host_listings_count_shared_rooms'
]

plot_correlation_heatmap(df, host_cols, 'Correlación entre variables de listings host')

"""El heatmap mostró correlaciones altas entre `host_listings_count`,`host_total_listings_count` y `calculated_host_listings_count`. Graficamos scatterplots para visualizar si la relación es  lineal y consistente."""

fig, axes = plt.subplots(1, 2, figsize=(14, 5))

axes[0].scatter(df['calculated_host_listings_count'], df['host_listings_count'], alpha=0.3, s=5)
axes[0].set_xlabel('calculated_host_listings_count')
axes[0].set_ylabel('host_listings_count')
axes[0].set_title('calculated vs host_listings_count')

axes[1].scatter(df['calculated_host_listings_count'], df['host_total_listings_count'], alpha=0.3, s=5)
axes[1].set_xlabel('calculated_host_listings_count')
axes[1].set_ylabel('host_total_listings_count')
axes[1].set_title('calculated vs host_total_listings_count')

plt.tight_layout()
plt.show()

"""Para complementar el análisis de correlaciones, visualizamos la distribución de cada variable mediante boxplots, lo que nos permite identificar diferencias de escala, varianza y presencia de outliers entre ellas."""

fig, axes = plt.subplots(2, 3, figsize=(16, 8))
axes = axes.flatten()

for i, col in enumerate(host_cols):
    axes[i].boxplot(df[col].dropna(), vert=True)
    axes[i].set_title(col, fontsize=9)
    axes[i].set_ylabel('Cantidad de listings')

plt.suptitle('Distribución de variables de listings del host', fontsize=12)
plt.tight_layout()
plt.show()

"""Del análisis conjunto (heatmap, scatterplots y boxplots) tomamos las siguientes decisiones:

- `calculated_host_listings_count_entire_homes` se elimina por tener correlación 1.00 con  `calculated_host_listings_count`, siendo prácticamente la misma variable. Esto se debe a que en Milán la gran mayoría de listings son entire homes.

- `calculated_host_listings_count_shared_rooms` se elimina por tener varianza casi nula (75% de valores en 0, máximo de 7).

- `host_listings_count` se elimina por ser ambigua según el diccionario y quedar redundante
entre `calculated_host_listings_count` (Milán) y `host_total_listings_count` (global).

- Se conservan `calculated_host_listings_count`, `host_total_listings_count` y
`calculated_host_listings_count_private_rooms` ya que cada una captura información distinta  y relevante para predecir el precio.
"""

host_drop_cols = [
    'host_listings_count',
    'calculated_host_listings_count_entire_homes',
    'calculated_host_listings_count_shared_rooms'
]
df = df.drop(columns=host_drop_cols)

"""### Analisis de las variables de cantidad de reviews

El dataset cuenta con múltiples variables que describen la cantidad de reseñas del listing en diferentes ventanas temporales. Analizamos si aportan información distinta o si algunas son redundantes entre sí.
"""

review_count_cols = [
    'number_of_reviews',
    'number_of_reviews_ltm',
    'number_of_reviews_l30d',
    'number_of_reviews_ly',
    'reviews_per_month'
]

plot_correlation_heatmap(df, review_count_cols, 'Correlación entre variables de cantidad de reviews')

fig, axes = plt.subplots(1, 5, figsize=(18, 4))

for i, col in enumerate(review_count_cols):
    axes[i].hist(df[col], bins=50, edgecolor='black')
    axes[i].set_title(col, fontsize=8)
    axes[i].set_xlabel('Cantidad')
    axes[i].set_ylabel('Frecuencia')

plt.suptitle('Distribución de variables de cantidad de reviews', fontsize=12)
plt.tight_layout()
plt.show()

print(df[review_count_cols].describe())

"""Los histogramas y estadísticas descriptivas muestran que `number_of_reviews_ltm` y `number_of_reviews_ly` tienen distribuciones prácticamente idénticas (rango 0-204 vs 0-203, medias 13.6 vs 11.3), y ademas muestran una alta correlación en el heatmap (0.82) por lo que eliminamos `number_of_reviews_ly`.

`reviews_per_month` presenta 2754 nulos y su información es derivable a partir de `number_of_reviews` y `first_review`, por lo que también se elimina.

Se conservan `number_of_reviews` (volumen histórico), `number_of_reviews_ltm` (actividad  reciente) y `number_of_reviews_l30d` (demanda actual), ya que cada una captura una ventana temporal distinta y complementaria.
"""

df = df.drop(columns=['number_of_reviews_ly', 'reviews_per_month'])

"""### Análisis de los review-scores"""

review_score_cols = [
    'review_scores_rating',
    'review_scores_accuracy',
    'review_scores_cleanliness',
    'review_scores_checkin',
    'review_scores_communication',
    'review_scores_location',
    'review_scores_value'
]

plot_correlation_heatmap(df, review_score_cols, 'Correlación entre variables de review scores')

"""Analizamos los scores de reviews mediante un heatmap de correlaciones. Si bien todas presentan correlaciones moderadas-altas entre sí (0.44-0.84), cada una mide un aspecto diferente de la experiencia del huésped: limpieza, ubicación, comunicación del host, check-in, precisión de la descripción y relación calidad/precio.

`review_scores_location` es la más independiente del resto (0.44-0.54), lo cual tiene sentido
ya que la ubicación es una característica objetiva del listing que no depende de la experiencia
con el host.

Dado que ninguna variable presenta redundancia y cada una captura información distinta, se conservan todas.

### Análisis del Dataframe post filtrado de columnas
"""

# Analizamos los tipos de cada variable
df.info()

# Porcentaje de nulos por columna
nulls = (df.isna().sum() / len(df) * 100).round(2)
nulls = nulls[nulls > 0].sort_values(ascending=False)
print(nulls.to_string())

def plot_distribucion(serie, titulo=''):
    fig, axes = plt.subplots(1, 2, figsize=(14, 4))

    axes[0].hist(serie, bins=100, edgecolor='black')
    axes[0].set_title(f'Distribución de {titulo}')
    axes[0].set_xlabel(titulo)
    axes[0].set_ylabel('Frecuencia')

    axes[1].boxplot(serie, vert=False)
    axes[1].set_title(f'Boxplot de {titulo}')
    axes[1].set_xlabel(titulo)

    plt.tight_layout()
    plt.show()

plot_distribucion(df['price'], 'price')

print(df['price'].describe())
print(f"\nPrecios en 0: {(df['price'] == 0).sum()}")

"""Dado que la distribución de `price` es fuertemente asimétrica, aplicamos la transformación `log1p` para acercarla a una distribución normal. Esto mejora el rendimiento de la Regresión Lineal, que asume una distribución simétrica del target. Guardamos el resultado en una nueva columna `price_log`, conservando `price` original para poder interpretar los resultados finales.

Ademas puede mejorar la calidad del posterior filtrado de outliers de esta variable

## Clasificación y correcciones de tipo de variables

Clasificamos las variables del dataset según su tipo para asegurar que cada una sea tratada correctamente en las etapas siguientes.

Distinguimos entre:
- **Cuantitativas continuas**: variables numéricas que pueden tomar cualquier valor en un rango (ej: `price`, `latitude`)
- **Cuantitativas discretas**: variables numéricas que toman valores enteros (ej: `accommodates`, `bedrooms`)
- **Cualitativas ordinales**: variables categóricas con un orden implícito (ej: `host_response_time`)
- **Cualitativas nominales**: variables categóricas sin orden (ej: `room_type`, `neighbourhood_cleansed`)

Además verificamos que los tipos de datos en el dataframe reflejen correctamente esta clasificación, corrigiendo los casos donde no sea así.

### Cambio a variables booleanas

Las variables booleanas vienen por defecto como un `object` donde `'t' = true` y `'f' = false`.
Las cambiamos al tipo `bool`, seteando los nulos como false en `host_has_profile_pic`, `has_availability` y `host_is_superhost` ya que si no hay suficiente información para determinar el valor de las viariables, según la lógica de negocio, lo más correcto sería interpretarlas como false.
"""

bool_cols = ['host_is_superhost', 'host_has_profile_pic', 'host_identity_verified',
             'has_availability', 'instant_bookable']

for col in bool_cols:
    df[col] = df[col].map({'t': True, 'f': False, None: False}).astype(bool)

df[bool_cols].dtypes

"""### Cambio a variables que representan porcentajes

Las variables que representan porcentajes vienen formateadas como un `float`. Le sacamos el caracter '%' y las dejamos como tipo `float`
"""

rate_cols = ['host_response_rate', 'host_acceptance_rate']

for col in rate_cols:
    df[col] = df[col].str.replace('%', '', regex=False).astype(float)

df[rate_cols].dtypes

"""### Cambio de las variables de fechas

Las variables `host_since`, `first_review` y `last_review` vienen como strings y las convertimos a `datetime`. En la etapa de Feature Engineering extraeremos variables numéricas derivadas de ellas, como la antigüedad del host o los días desde la última review.
"""

date_cols = ['host_since', 'first_review', 'last_review']
for col in date_cols:
    df[col] = pd.to_datetime(df[col])

"""### Cambios a `host_response_time`

Es una variable cualitiva ordinal con un orden implicito:
+ ""within an hour"
+ "within a few hours"
+ "within a day"
+ "a few days or more"
"""

order = ['within an hour', 'within a few hours', 'within a day', 'a few days or more']
df['host_response_time'] = pd.Categorical(df['host_response_time'], categories=order, ordered=True)

"""### Forma del dataframe luego de cambiar los tipos"""

print(df.dtypes)

"""## Filtros por regla de negocio

Antes de continuar con el análisis, eliminamos las filas que representan errores de carga  o propiedades que escapan a la lógica de un alquiler en Milán. Se opta por un filtrado  basado en **reglas de negocio** en lugar de Z-score modificado, porque al estar basado  en la mediana (con distribuciones asimétricas), generaría muchos falsos positivos.

Por ejemplo, una propiedad de 3 baños es completamente válida pero el Z-score podría marcarla como outlier dado que la mayoría tiene 1 o 2.
"""

# Configuración de las variables y sus límites de negocio
variables_capacidad = {
    'accommodates': 16,
    'bedrooms': 8,
    'beds': 12,
    'bathrooms': 6
}

fig, axes = plt.subplots(2, 2, figsize=(14, 10))
axes = axes.flatten()

for i, (col, limite_negocio) in enumerate(variables_capacidad.items()):
    ax = axes[i]
    serie = df[col].dropna()
    plot_data = serie[serie <= limite_negocio * 1.5]
    sns.histplot(plot_data, discrete=True, color='skyblue', edgecolor='black', ax=ax)
    median_val = serie.median()
    mad_val = (serie - median_val).abs().median()
    if mad_val > 0:
        corte_zscore = (3.5 * mad_val / 0.6745) + median_val
    else:
        corte_zscore = median_val + 0.5

    ax.axvline(x=corte_zscore, color='red', linestyle='--', linewidth=2, label='Corte Z-score (Falso Positivo)')
    ax.axvline(x=limite_negocio, color='green', linestyle='-', linewidth=2, label='Corte Regla Negocio')

    ax.set_title(f'Distribución de {col.capitalize()}', fontsize=12)
    ax.set_xlabel('Cantidad')
    ax.set_ylabel('Frecuencia')
    ax.legend()

plt.suptitle('Comparación de criterios de corte: Z-score vs. Regla de Negocio', fontsize=13, y=1.00)
plt.tight_layout()
plt.show()

"""El gráfico muestra que el corte por Z-score sería demasiado conservador (línea roja), descartando propiedades con valores físicamente válidos. El corte por regla de negocio (línea verde) preserva esos casos legítimos y solo elimina valores extremos imposibles."""

# Filtro de noches mínimas. Corto en 200 dias
df = df[df['minimum_nights'] <= 200]

# Filtro de capacidad (dejando los nulos intactos si los hubiera para imputarlos después)
df = df[(df['accommodates'] <= 16)]
df = df[(df['bedrooms'].isna()) | (df['bedrooms'] <= 8)]
df = df[(df['beds'].isna()) | (df['beds'] <= 12)]
df = df[(df['bathrooms'].isna()) | (df['bathrooms'] <= 6)]

"""## Análisis exploratorio

### Distribuciones univariadas - Numericas
"""

numeric_cols = df.select_dtypes(include=['int64', 'float64']).columns.tolist()
numeric_cols = [col for col in numeric_cols if col not in ['price', 'price_log']]

fig, axes = plt.subplots(len(numeric_cols), 2, figsize=(14, len(numeric_cols) * 3))

for i, col in enumerate(numeric_cols):
    axes[i, 0].hist(df[col].dropna(), bins=50, edgecolor='black')
    axes[i, 0].set_title(f'Distribución de {col}')
    axes[i, 0].set_xlabel(col)
    axes[i, 0].set_ylabel('Frecuencia')

    axes[i, 1].boxplot(df[col].dropna(), vert=False)
    axes[i, 1].set_title(f'Boxplot de {col}')
    axes[i, 1].set_xlabel(col)

plt.tight_layout()
plt.show()

"""#### Conclusiones del análisis univariado de variables numéricas

**Variables de respuesta del host** (`host_response_rate`, `host_acceptance_rate`): ambas están fuertemente concentradas cerca del 100%, indicando que la mayoría de los hosts responden y aceptan solicitudes casi siempre. Los valores bajos son outliers reales que representan hosts poco activos.

---

**Variables geográficas** (`latitude`, `longitude`): presentan distribuciones bimodales, sugiriendo que los listings se concentran en dos zonas geográficas distintas de Milán. No se detectan outliers problemáticos.

---

**Variables de capacidad** (`accommodates`, `bathrooms`, `bedrooms`, `beds`): todas presentan distribuciones asimétricas concentradas en valores bajos (1-4), con outliers hacia valores altos.
Es esperable dado que la mayoría son apartamentos pequeños. Los valores extremos (hasta 20 baños, 10 habitaciones) corresponden probablemente a hoteles o propiedades de lujo legítimas.

---

**Variables de noches** (`minimum_nights`, `maximum_nights`, `minimum_nights_avg_ntm`, `maximum_nights_avg_ntm`): `maximum_nights` y `maximum_nights_avg_ntm` presentan picos marcados en valores específicos (365, 1125) que corresponden a valores default que los hosts configuran sin criterio. `minimum_nights` presenta una cola larga con outliers reales.

---

**Variables de disponibilidad** (`availability_30`, `availability_365`): `availability_30` muestra una distribución relativamente uniforme. `availability_365` tiene un pico en 365 (siempre disponible), correspondiente a listings gestionados profesionalmente.

---

**Variables de reviews** (`number_of_reviews`, `number_of_reviews_ltm`, `number_of_reviews_l30d`): todas presentan distribuciones muy asimétricas con cola larga. La mayoría de los listings tienen
pocas reviews, con outliers de hasta 1400 reviews históricas. En Feature Engineering se evaluará aplicar transformación logarítmica a estas variables.

---

**Review scores** (`review_scores_*`): todos los scores están fuertemente concentrados entre 4.5 y 5.0, con outliers hacia valores bajos. Esto refleja un sesgo de supervivencia típico de la plataforma: los listings con malas reviews tienden a desaparecer. Los valores entre 1.0 y 2.0 son outliers reales pero poco frecuentes.

---

**Variables de listings del host** (`calculated_host_listings_count`,
`calculated_host_listings_count_private_rooms`): ambas muy asimétricas. La mayoría de los hosts tienen pocos listings, pero existe una cola de hosts con cientos de propiedades que corresponden a agencias de gestión profesional.

### Distribuciones univariadas - Categoricas

Analizamos la distribución de las variables categóricas, agrupándolas por tipo:
booleanas, ordinales, nominales de baja cardinalidad y nominales de alta cardinalidad.

Cada grupo requiere un tipo de visualización distinto.
"""

# Función auxiliar para countplot con porcentajes
def plot_categorica(serie, titulo, ax=None, top_n=None, rotacion=0):
    if ax is None:
        fig, ax = plt.subplots(figsize=(8, 5))
    counts = serie.value_counts(dropna=False)
    if top_n is not None:
        counts = counts.head(top_n)
    total = counts.sum()
    pct = (counts / total * 100).round(1)
    bars = ax.bar(counts.index.astype(str), counts.values, color='#2196F3', edgecolor='black')
    ax.set_title(titulo)
    ax.set_xlabel('Categoría')
    ax.set_ylabel('Cantidad de listings')
    ax.tick_params(axis='x', rotation=rotacion)
    for bar, p in zip(bars, pct):
        ax.text(bar.get_x() + bar.get_width()/2, bar.get_height(),
                f'{p}%', ha='center', va='bottom', fontsize=8)

"""#### Variables booleanas

Verificamos el grado de balance/desbalance de las variables binarias. Variables muy desbalanceadas (>95% en una categoría) suelen tener bajo poder predictivo.
"""

bool_cols = ['host_is_superhost', 'host_has_profile_pic', 'host_identity_verified',
             'has_availability', 'instant_bookable', 'has_license']

fig, axes = plt.subplots(2, 3, figsize=(15, 8))
axes = axes.flatten()
for ax, col in zip(axes, bool_cols):
    plot_categorica(df[col], col, ax=ax)
plt.suptitle('Distribución de variables booleanas', fontsize=14, y=1.02)
plt.tight_layout()
plt.show()

"""`host_is_superhost` y `instant_bookable` son variables bien balanceadas, por lo que tienen un buen potencial predictivo.

`host_has_profile_pic`, `host_identity_verified` y `has_availability` tienen el 93% o más en una sola categoría, esto genera que sean constantes prácticamente y no aportan nada al análisis.

`has_license` esta desbalanceada pero la conservamos ya que tiene valor predictivo, listings sin licencia probablemente tengan un perfil distinto y vale la pena estudiarla en relación a price.
"""

cols_casi_constantes = ['host_has_profile_pic', 'has_availability', 'host_identity_verified']

df = df.drop(columns=cols_casi_constantes)

"""#### Variable ordinal"""

fig, ax = plt.subplots(figsize=(10, 5))
counts = df['host_response_time'].value_counts(dropna=False).reindex(
    ['within an hour', 'within a few hours', 'within a day', 'a few days or more', np.nan]
)
counts.index = [str(i) if pd.notna(i) else 'NaN' for i in counts.index]
total = counts.sum()
pct = (counts / total * 100).round(1)
bars = ax.bar(counts.index, counts.values,
              color=['#4CAF50', '#8BC34A', '#FFC107', '#F44336', '#9E9E9E'],
              edgecolor='black')
ax.set_title('Distribución de host_response_time (ordinal)')
ax.set_xlabel('Tiempo de respuesta del host')
ax.set_ylabel('Cantidad de listings')
for bar, p in zip(bars, pct):
    ax.text(bar.get_x() + bar.get_width()/2, bar.get_height(),
            f'{p}%', ha='center', va='bottom', fontsize=9)
plt.tight_layout()
plt.show()

"""Muy concentrada en `within an hour` (71.7%) seguida muy de lejos por las demás. La distribución refleja un mercado donde la mayoría de hosts en Milán responde rápido para mantenerse competitivo en el ranking de Airbnb.

Hay 13.2% de NaN que corresponden a hosts que no tienen suficientes datos de respuesta (probablemente nuevos o con muy poca actividad). El tratamiento natural es convertir el NaN en una categoría propia `No data`.

#### Nominales de baja cardinalidad `room_type`
"""

fig, ax = plt.subplots(figsize=(9, 5))
plot_categorica(df['room_type'], 'Distribución de room_type', ax=ax)
plt.tight_layout()
plt.show()

"""Mercado dominado por `Entire home/apt (89.3%)`. Esto confirma que el mercado de Airbnb en Milán es esencialmente de departamentos enteros, hay muy poca oferta de habitaciones privadas (10.5%) y prácticamente nada de compartidas (0.2%) ni hoteles (0%).

#### Nominales de alta cardinalidad `property_type`

Esta variable tiene muchas categorías. Mostramos solo las top 15 por frecuencia. Las categorías con muy bajo conteo serán candidatas a colapsarse en una categoría 'Other' durante la fase de feature engineering / encoding.
"""

n_property = df['property_type'].nunique()
print(f"Cantidad total de categorías en property_type: {n_property}")
print(f"Top 5 categorías acumulan: "
      f"{df['property_type'].value_counts(normalize=True).head(5).sum() * 100:.1f}% del total")

fig, ax = plt.subplots(figsize=(12, 6))
top_property = df['property_type'].value_counts().head(15)
ax.barh(top_property.index[::-1], top_property.values[::-1], color='#2196F3', edgecolor='black')
ax.set_title(f'Top 15 categorías de property_type (de {n_property} totales)')
ax.set_xlabel('Cantidad de listings')
ax.set_ylabel('Tipo de propiedad')
plt.tight_layout()
plt.show()

"""Las top 5 categorías acumulan el 92.9% de los listings, lo recomendable sería agrupar todas la categorías con menos del 1% de los listings en `Other`.

#### Nominales de muy alta cardinalidad `neighbourhood_cleansed`

Los 88 barrios de Milán son demasiados para visualizar individualmente Mostramos los 20 más frecuentes y luego analizaremos el desafío del encoding
para esta variable.
"""

n_barrios = df['neighbourhood_cleansed'].nunique()
print(f"Cantidad total de barrios: {n_barrios}")
print(f"Top 10 barrios acumulan: "
      f"{df['neighbourhood_cleansed'].value_counts(normalize=True).head(10).sum() * 100:.1f}% del total")

fig, ax = plt.subplots(figsize=(12, 7))
top_barrios = df['neighbourhood_cleansed'].value_counts().head(20)
ax.barh(top_barrios.index[::-1], top_barrios.values[::-1], color='#42A5F5', edgecolor='black')
ax.set_title(f'Top 20 barrios de Milán por cantidad de listings (de {n_barrios} totales)')
ax.set_xlabel('Cantidad de listings')
ax.set_ylabel('Barrio')
plt.tight_layout()
plt.show()

"""Esta es la variable categórica mas desafiante del dataset, ya que One-hot encoding generaría 87 columnas adicionales, siendo ineficiente y problemático. Esto aumenta drásticamente la dimensionalidad y empeora el desempeño de regresión lineal por la dispersión.

Se podría solucionar con Frequency encoding, reemplazando barrio por su frecuencia o mediante agrupación geográfica, usar `latitude`/`longitude` en lugar de barrio o agrupar por zonas.

### Matriz de nulos

Para decidir cómo tratar los nulos no alcanza con saber cuántos hay por variable. Necesitamos entender si los nulos aparecen de forma **aleatoria** o si siguen patrones estructurales (variables que están nulas juntas en las mismas filas).
"""

# Commented out IPython magic to ensure Python compatibility.
# Instalación de missingno (optimizaciones específicas para datasets grandes)
# %pip install -q missingno
import missingno as msno

"""Después de las eliminaciones de columnas, vemos qué variables aún tienen nulos."""

nulls_resumen = df.isna().sum()
nulls_resumen = nulls_resumen[nulls_resumen > 0].sort_values(ascending=False)
nulls_pct = (nulls_resumen / len(df) * 100).round(2)

resumen_nulos = pd.DataFrame({
    'cantidad_nulos': nulls_resumen,
    'porcentaje': nulls_pct
})
print(resumen_nulos.to_string())

"""#### Matriz visual de nulos"""

cols_con_nulos = nulls_resumen.index.tolist()

fig, ax = plt.subplots(figsize=(14, 6))
msno.matrix(df[cols_con_nulos].sample(min(1500, len(df)), random_state=42),
            ax=ax, sparkline=False)
ax.set_title('Matriz de valores nulos (muestra de 1500 filas)', fontsize=12, pad=10)
plt.tight_layout()
plt.show()

"""Cada fila del gráfico es una observación del dataset, cada columna una variable. Las líneas blancas indican valores nulos. Si dos columnas tienen líneas blancas alineadas, sus nulos coinciden en las mismas filas.

#### Heatmap de correlación entre nulos

El heatmap cuantifica la relación entre los patrones de nulos:
- Valores cercanos a **1**: las dos variables tienden a estar nulas en las mismas filas
- Valores cercanos a **-1**: cuando una está nula, la otra tiende a estar presente
- Valores cercanos a **0**: nulos independientes entre sí
"""

fig, ax = plt.subplots(figsize=(11, 8))
nulls_corr = df[cols_con_nulos].isna().corr()
sns.heatmap(nulls_corr,
            annot=True, fmt='.2f',
            cmap='coolwarm', vmin=-1, vmax=1,
            center=0, linewidths=0.5,
            cbar_kws={'label': 'Correlación de nulos'}, ax=ax)
ax.set_title('Correlación entre patrones de nulos', fontsize=13, pad=12)
plt.xticks(rotation=45, ha='right')
plt.yticks(rotation=0)
plt.tight_layout()
plt.show()

"""Hipótesis 1: los listings sin reviews tienen nulos en todas las variables relacionadas con reviews."""

# Hipótesis 1
review_cols = ['first_review', 'last_review', 'reviews_per_month',
               'review_scores_rating', 'review_scores_accuracy',
               'review_scores_cleanliness', 'review_scores_checkin',
               'review_scores_communication', 'review_scores_location',
               'review_scores_value']

# Los nulos de review_scores_rating coinciden con number_of_reviews == 0?
sin_reviews = df['number_of_reviews'] == 0
nulos_rating = df['review_scores_rating'].isna()

print("Hipótesis 1: nulos de reviews coinciden con listings sin reviews")
print(f"  Listings con number_of_reviews = 0: {sin_reviews.sum():,}")
print(f"  Listings con review_scores_rating nulo: {nulos_rating.sum():,}")
print(f"  Coinciden ambas condiciones: {(sin_reviews & nulos_rating).sum():,}")
print(f"  Coincidencia (%): {(sin_reviews == nulos_rating).mean() * 100:.2f}%\n")

"""Hipótesis 2: los hosts sin actividad de respuesta tienen nulos en host_response_time y host_response_rate juntos."""

# Hipótesis 2
nulos_response_time = df['host_response_time'].isna()
nulos_response_rate = df['host_response_rate'].isna()

print("Hipótesis 2: nulos de host_response_time y host_response_rate coinciden")
print(f"  Nulos de host_response_time: {nulos_response_time.sum():,}")
print(f"  Nulos de host_response_rate: {nulos_response_rate.sum():,}")
print(f"  Coinciden ambas condiciones: {(nulos_response_time & nulos_response_rate).sum():,}")
print(f"  Coincidencia (%): {(nulos_response_time == nulos_response_rate).mean() * 100:.2f}%")

"""### Análisis bivariado — features vs price_log

#### Numéricas vs `price_log`

Para cada variable numérica calculamos:

- **Pearson:** mide relación lineal (qué tan bien se ajusta una línea recta)
- **Spearman:** mide relación monotónica (la variable crece/decrece consistentemente con price, no necesariamente lineal)
"""

from scipy.stats import pearsonr, spearmanr

num_features = ['accommodates', 'bedrooms', 'beds', 'bathrooms',
                'minimum_nights', 'maximum_nights',
                'number_of_reviews', 'number_of_reviews_ltm',
                'review_scores_rating', 'review_scores_value',
                'review_scores_location', 'review_scores_cleanliness',
                'host_response_rate', 'host_acceptance_rate',
                'host_total_listings_count', 'calculated_host_listings_count',
                'availability_30', 'availability_365', 'review_scores_accuracy',
                'review_scores_checkin', 'review_scores_communication']

corr_results = []
for col in num_features:
    sub = df[[col, 'price_log']].dropna()
    if len(sub) < 100:
        continue
    pearson_r, _ = pearsonr(sub[col], sub['price_log'])
    spearman_r, _ = spearmanr(sub[col], sub['price_log'])
    corr_results.append({
        'feature': col,
        'pearson': round(pearson_r, 3),
        'spearman': round(spearman_r, 3),
        'abs_spearman': round(abs(spearman_r), 3)
    })

corr_df = pd.DataFrame(corr_results).sort_values('abs_spearman', ascending=False)
print(corr_df.drop(columns='abs_spearman').to_string(index=False))

"""Graficamos las top 6 features con mayor correlación (en valor absoluto) contra `price_log`."""

top_features = corr_df.head(6)['feature'].tolist()

fig, axes = plt.subplots(2, 3, figsize=(16, 9))
axes = axes.flatten()

for ax, col in zip(axes, top_features):
    sub = df[[col, 'price_log']].dropna().sample(min(3000, len(df)), random_state=42)
    ax.scatter(sub[col], sub['price_log'], alpha=0.25, s=8, color='#2196F3')
    pearson_r = corr_df.loc[corr_df['feature'] == col, 'pearson'].values[0]
    spearman_r = corr_df.loc[corr_df['feature'] == col, 'spearman'].values[0]
    ax.set_title(f'{col}\nPearson={pearson_r}, Spearman={spearman_r}', fontsize=10)
    ax.set_xlabel(col)
    ax.set_ylabel('price_log')

plt.suptitle('Top 6 features numéricas vs price_log', fontsize=13, y=1.00)
plt.tight_layout()
plt.show()

"""Las variables de **capacidad del listing** (`accommodates`, `bedrooms`, `bathrooms`, `beds`) son las que mayor correlación presentan con `price_log`, con Spearman entre 0.28 y 0.39. La relación es positiva y esperable: a mayor capacidad, mayor precio. Los scatterplots muestran columnas verticales debido a que estas variables son discretas. Si bien hay dispersión entre los puntos, se puede observar una tendencia al aumento de precio cuanto mas altas son las variables de capacidad

`accommodates` es la feature más correlacionada con `price_log` (Pearson=0.41, Spearman=0.39), lo que tiene sentido ya que la capacidad máxima es el factor más directo en la fijación del precio.

`host_acceptance_rate` y `review_scores_location` presentan correlaciones más débiles (Spearman ~0.23), aunque positivas. Un host con alta tasa de aceptación y una buena ubicación tienden a cobrar algo más, pero la relación es ruidosa y con mucha dispersión.

En general, ninguna variable numérica tiene una correlación muy alta con `price_log`, lo que sugiere que el precio depende de una combinación de factores más que de una sola variable dominante.

#### Categóricas y booleanas vs `price_log`
"""

# room_type
fig, axes = plt.subplots(1, 2, figsize=(15, 5))

orden_room = df.groupby('room_type', observed=True)['price_log'].median().sort_values(ascending=False).index
sns.boxplot(data=df, x='room_type', y='price_log', ax=axes[0],
            order=orden_room, color='#42A5F5')
axes[0].set_title('price_log por room_type')
axes[0].set_xlabel('Tipo de habitación')
axes[0].set_ylabel('price_log')
axes[0].tick_params(axis='x', rotation=15)

# host_response_time (ordinal)
orden_resp = ['within an hour', 'within a few hours', 'within a day', 'a few days or more']
sns.boxplot(data=df.dropna(subset=['host_response_time']),
            x='host_response_time', y='price_log',
            ax=axes[1], order=orden_resp, color='#66BB6A')
axes[1].set_title('price_log por host_response_time')
axes[1].set_xlabel('Tiempo de respuesta del host')
axes[1].set_ylabel('price_log')
axes[1].tick_params(axis='x', rotation=15)

plt.tight_layout()
plt.show()

"""+ **`room_type`** es una de las variables categóricas con mayor diferencia de precio entre categorías. Los `Hotel room` tienen la mediana más alta, seguidos por `Entire home/apt`, `Private room` y finalmente `Shared room` como los más baratos. La diferencia entre `Entire home/apt` y `Shared room` es considerable, lo que confirma que el tipo de habitación es un factor relevante para predecir el precio.

+ **`host_response_time`** presenta una tendencia donde los hosts que responden más rápido (`within an hour`) tienden a cobrar precios ligeramente más altos.
Aunque en el box-plot se ve la superposición de las cajas, mostrando que no es una tendencia tan marcada como en `room_type`
"""

# Booleanas
bool_features = ['host_is_superhost', 'instant_bookable', 'has_license']

fig, axes = plt.subplots(1, 3, figsize=(14, 4))
for ax, col in zip(axes, bool_features):
    sub = df.dropna(subset=[col])
    sns.boxplot(data=sub, x=col, y='price_log', ax=ax, hue=col, palette=['#EF5350', '#66BB6A'], legend=False)
    median_diff = (sub.groupby(col, observed=True)['price_log'].median().diff().iloc[-1])
    ax.set_title(f'{col}\nΔ mediana log: {median_diff:.3f}')
    ax.set_xlabel(col)
    ax.set_ylabel('price_log')

plt.suptitle('Booleanas vs price_log', fontsize=12, y=1.02)
plt.tight_layout()
plt.show()

"""+ **`host_is_superhost`** muestra un resultado contraintuitivo: los superhosts tienen una mediana de precio ligeramente **menor** (Δ = -0.091). Una posible explicación es que los superhosts priorizan aumentar los clientes por sobre el precio para acumular buenas reseñas.

+ **`instant_bookable`** presenta la diferencia más marcada (Δ = 0.278): los listings con reserva instantánea tienen precios más altos.

+ **`has_license`** también muestra una diferencia positiva (Δ = 0.209): los listings con licencia oficial tienden a ser más caros.

#### Top 10 categorías de `property_type` por precio mediano

Como property_type tiene 50 categorías, mostramos solo las top 10 por frecuencia y analizamos si alguna se destaca por precio.
"""

top_property = df['property_type'].value_counts().head(10).index
sub_property = df[df['property_type'].isin(top_property)]

orden_property = sub_property.groupby('property_type', observed=True)['price_log']\
                            .median().sort_values(ascending=False).index

fig, ax = plt.subplots(figsize=(13, 6))
sns.boxplot(data=sub_property, x='property_type', y='price_log',
            order=orden_property, color='#42A5F5', ax=ax)
ax.set_title('price_log por property_type (top 10 más frecuentes)')
ax.set_xlabel('Tipo de propiedad')
ax.set_ylabel('price_log')
ax.tick_params(axis='x', rotation=30)
plt.setp(ax.get_xticklabels(), ha='right')
plt.tight_layout()
plt.show()

"""**`property_type`** muestra grandes diferencias de precio entre sus categorías. Los `Entire serviced apartment` tienen la mediana más alta, seguidos por `Room in hotel` y `Entire home`. Esto puede explicarse como que a mayor privacidad y más servicios aumentan los precios.

En el extremo inferior se encuentran `Private room in rental unit` y `Private room in condo`, que comparten espacio con otras personas y por ende tienen precios significativamente menores.

Las categorías `Entire *` en general cobran más que las `Private room *`, lo que es consistente con lo observado en `room_type`. Esto sugiere que hay cierta redundancia de información entre `property_type` y `room_type`.

#### Top 15 barrios por precio mediano

Para `neighbourhood_cleansed` ordenamos los barrios por precio mediano descendente y mostramos los 15 más caros y los 15 más baratos.
"""

medianas_barrio = df.groupby('neighbourhood_cleansed', observed=True)['price_log']\
                    .agg(['median', 'count'])\
                    .query('count >= 50')\
                    .sort_values('median', ascending=False)

fig, axes = plt.subplots(1, 2, figsize=(15, 6))

top15_caros = medianas_barrio.head(15)
axes[0].barh(top15_caros.index[::-1], top15_caros['median'][::-1], color='#EF5350')
axes[0].set_title('Top 15 barrios más caros (price_log mediano)')
axes[0].set_xlabel('price_log mediano')

top15_baratos = medianas_barrio.tail(15)
axes[1].barh(top15_baratos.index[::-1], top15_baratos['median'][::-1], color='#66BB6A')
axes[1].set_title('Top 15 barrios más baratos (price_log mediano)')
axes[1].set_xlabel('price_log mediano')

plt.tight_layout()
plt.show()

"""**`neighbourhood_cleansed`** muestra diferencias de precio claras entre barrios. Los barrios más caros son **DUOMO** y **BRERA**, los dos barrios más turísticos y céntricos de Milán, las zonas que le siguen tambien son centricas.

En el extremo opuesto, los barrios más baratos como **QUARTO OGGIARO**, **BAGGIO** y **FORZE ARMATE** son zonas periféricas de Milán, alejadas del centro turístico.

La diferencia entre el barrio más caro (DUOMO, ~5.5) y el más barato (QUARTO OGGIARO ~4.3) es de aproximadamente 1.2. Si esta diferencia la transladamos a la escala original de `price`, representa una diferencia de precio de más del triple.
"""

barrios = df[df['neighbourhood_cleansed'].isin(['DUOMO', 'QUARTO OGGIARO'])]
medianas = barrios.groupby('neighbourhood_cleansed')['price'].median()

fig, ax = plt.subplots(figsize=(6, 4))
ax.bar(medianas.index, medianas.values, color=['#66BB6A', '#EF5350'])
ax.set_title('Precio mediano: DUOMO vs QUARTO OGGIARO')
ax.set_ylabel('price')
for i, v in enumerate(medianas.values):
    ax.text(i, v + 1, f'{v:.0f}', ha='center', fontweight='bold')
plt.tight_layout()
plt.show()

"""#### Distribución geográfica del precio

Visualizamos el precio sobre el mapa de Milán usando latitud y longitud. Los colores cálidos indican mayor precio.
"""

fig, ax = plt.subplots(figsize=(10, 10))
sub_geo = df[['latitude', 'longitude', 'price_log']].sample(min(8000, len(df)), random_state=42)
sc = ax.scatter(sub_geo['longitude'], sub_geo['latitude'],
                c=sub_geo['price_log'], cmap='viridis',
                alpha=0.5, s=8)
plt.colorbar(sc, label='price_log')
ax.set_title('Distribución geográfica del precio en Milán')
ax.set_xlabel('Longitud')
ax.set_ylabel('Latitud')
plt.tight_layout()
plt.show()

"""El mapa de calor confirma visualmente lo observado en el análisis por barrios: los precios más altos (colores amarillos/verdes) se concentran en el **centro de Milán**, alrededor de las coordenadas (9.18, 45.46), que corresponde a la zona del DUOMO y BRERA. A medida que nos alejamos del centro hacia la periferia, los precios caen.

Estas dos variables `latitude` y `longitude` capturan la informacion del barrio como variables cuantitativas continuas, mientras que `neighbourhood_cleansed` lo captura como una cualitativa nominal.

### Heatmap de correlaciones entre features (multicolinealidad)

Hasta ahora analizamos cómo cada feature se relaciona con price_log

Continuamos con analizando cómo se relacionan las features entre sí con el objetivo de detectar multicolinealidad.
"""

# Calculamos correlación de Spearman (más robusta a relaciones no lineales que Pearson)
corr_matrix = df[num_features].corr(method='spearman')

# Heatmap completo
fig, ax = plt.subplots(figsize=(14, 11))
mask = np.triu(np.ones_like(corr_matrix, dtype=bool), k=1)  # mascara triangular superior
sns.heatmap(corr_matrix, mask=mask,
            annot=True, fmt='.2f',
            cmap='coolwarm', vmin=-1, vmax=1, center=0,
            linewidths=0.5,
            cbar_kws={'label': 'Correlación de Spearman'},
            ax=ax)
ax.set_title('Matriz de correlación entre features numéricas (Spearman)',
             fontsize=13, pad=12)
plt.xticks(rotation=45, ha='right')
plt.yticks(rotation=0)
plt.tight_layout()
plt.show()

# Extraer pares únicos del triángulo superior
pares = []
for i in range(len(corr_matrix.columns)):
    for j in range(i + 1, len(corr_matrix.columns)):
        var1 = corr_matrix.columns[i]
        var2 = corr_matrix.columns[j]
        corr = corr_matrix.iloc[i, j]
        if abs(corr) > 0.7:
            pares.append({
                'feature_1': var1,
                'feature_2': var2,
                'correlación': round(corr, 3),
                'abs_corr': round(abs(corr), 3)
            })

pares_df = pd.DataFrame(pares).sort_values('abs_corr', ascending=False).drop(columns='abs_corr')
print("Pares de features con |correlación| > 0.7:")
print(pares_df.to_string(index=False) if len(pares_df) > 0 else "No hay pares con correlación > 0.7")

"""`host_total_listings_count` con `calculated_host_listings_count` tienen la correlación mas alta y tiene sentido, ambas cuentan listings del mismo host, una a nivel global y otra solo en Milán.

Por lo que eliminar `host_total_listings_count` tiene sentido porque tiene demasiada correlación con la otra variable que vamos a conservar.

---

`number_of_reviews` con `number_of_reviews_ltm` tienen 0.8 de correlacion, esta última captura actividad reciente, lo cual es más relevante para predecir el precio actual. El total histórico puede inflar la importancia de listings antiguos pero ya inactivos.

---

`accommodates` y `beds` correlacionan en 0.729, justo en el límite del criterio. Conservamos ambas porque capturan dimensiones distintas: `accommodates` mide capacidad humana y `beds` mide infraestructura.

---

Las 6 variables sub-puntaje correlacionan fuerte con rating (0.66-0.78) y entre sí (0.39-0.71). Esto es multicolinealidad, el puntaje global ya resume toda esta información.

El dato más importante: `review_scores_location sigue siendo distinta

Mantiene correlación de solo 0.46 con `rating` y entre 0.39-0.46 con las demás `review_scores`. Esto confirma que la percepción de ubicación es independiente de la percepción de calidad del alojamiento.

Decidimos conservar `review_scores_rating` y `review_scores_location`.
"""

cols_drop_multicolinealidad = [
    'host_total_listings_count',
    'number_of_reviews',
    'review_scores_value',
    'review_scores_accuracy',
    'review_scores_cleanliness',
    'review_scores_communication',
    'review_scores_checkin',
]

df = df.drop(columns=cols_drop_multicolinealidad)

"""## Split train/test

Procedemos a realizar la división del conjunto de datos en Entrenamiento (80%) y Prueba (20%).

Hacemos esta separación antes de comenzar con la imputacion de valores nulos, ya que vamos a usar metodos que usan la mediana o aprenden de las distribuciones.

Al aislarlo ahora evitamos cumplimos con que el conjunto de prueba sea totalmente desconocido, garantizando una simulación más real
"""

from sklearn.model_selection import train_test_split

print(f"Dimensiones del dataset antes del split: {df.shape}")

X = df.drop(columns=['price', 'price_log'])
y = df['price']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

y_train_log = np.log1p(y_train)
y_test_log  = np.log1p(y_test)

print("\n--- Resultados del Split ---")
print(f"Dimensiones de X_train (Entrenamiento): {X_train.shape}")
print(f"Dimensiones de X_test (Prueba): {X_test.shape}")

# Construir df_train para el EDA
df_train = X_train.copy()
df_train['price'] = y_train.values

"""## Feature Engineering

### Flags de ciclo de vida del listing: `has_reviews` e `is_active`

Detectamos que `last_review.notna()` y `number_of_reviews_ltm > 0` no coinciden: 2.058 listings (~13%) tienen reviews históricas pero ninguna en el último año.

Creamos dos flags complementarias:
- **`has_reviews`**: el listing recibió alguna review en su historia
- **`is_active`**: el listing recibió reviews en los últimos 12 meses

La combinación captura tres estados distintos:
- **Nuevo** (has_reviews=0, is_active=0)
- **Dormant** (has_reviews=1, is_active=0)
- **Activo** (has_reviews=1, is_active=1)
"""

# Verificación de coincidencia entre criterios para has_reviews
crit1 = X_train['number_of_reviews_ltm'] > 0
crit2 = X_train['last_review'].notna()

print(f"Listings con number_of_reviews_ltm > 0: {crit1.sum():,}")
print(f"Listings con last_review notna: {crit2.sum():,}")
print(f"Coinciden ambas condiciones: {(crit1 == crit2).sum():,} ({(crit1 == crit2).mean() * 100:.2f}%)")

# has_reviews: alguna vez tuvo review
X_train['has_reviews'] = X_train['last_review'].notna().astype(int)
X_test['has_reviews'] = X_test['last_review'].notna().astype(int)

# is_active: tuvo reviews en los últimos 12 meses
X_train['is_active'] = (X_train['number_of_reviews_ltm'] > 0).astype(int)
X_test['is_active'] = (X_test['number_of_reviews_ltm'] > 0).astype(int)

# has_response_data: el host tiene historial de respuesta
X_train['has_response_data'] = X_train['host_response_time'].notna().astype(int)
X_test['has_response_data'] = X_test['host_response_time'].notna().astype(int)

# Verificación de los tres ciclos de vida
print("Distribución de ciclos de vida en train:")
ciclos = X_train.groupby(['has_reviews', 'is_active']).size().reset_index(name='cantidad')
ciclos['estado'] = ciclos.apply(
    lambda r: 'Activo' if r['is_active'] == 1
    else ('Dormant' if r['has_reviews'] == 1 else 'Nuevo'),
    axis=1
)
ciclos['porcentaje'] = (ciclos['cantidad'] / len(X_train) * 100).round(2)
print(ciclos[['estado', 'cantidad', 'porcentaje']].to_string(index=False))

print("\nDistribución de has_response_data en train:")
print(X_train['has_response_data'].value_counts(normalize=True).round(3))

"""### Variables temporales

Convertimos las variables datetime (`host_since`, `first_review`, `last_review`) en medidas de edad en días desde la fecha del scrape (2025-09-22).

Esto permite usar la información temporal como features numéricas para los modelos.

**Fecha de referencia fija:** se usa la fecha del scrape (no `pd.Timestamp.now()`) para garantizar reproducibilidad y consistencia con el momento real de captura de los datos.

Los nulos generados (en listings sin reviews) se tratan en el bloque de tratamiento de nulos. La flag `has_reviews` ya creada marca estos casos especiales.
"""

# Fecha de referencia: día del scrape (extraído de la URL del dataset de Inside Airbnb)
SCRAPE_DATE = pd.Timestamp('2025-09-22')

# Asegurar que las columnas son datetime
for col in ['host_since', 'first_review', 'last_review']:
    X_train[col] = pd.to_datetime(X_train[col], errors='coerce')
    X_test[col] = pd.to_datetime(X_test[col], errors='coerce')

# Crear features temporales
X_train['host_age_days'] = (SCRAPE_DATE - X_train['host_since']).dt.days
X_test['host_age_days'] = (SCRAPE_DATE - X_test['host_since']).dt.days

X_train['listing_age_days'] = (SCRAPE_DATE - X_train['first_review']).dt.days
X_test['listing_age_days'] = (SCRAPE_DATE - X_test['first_review']).dt.days

X_train['days_since_last_review'] = (SCRAPE_DATE - X_train['last_review']).dt.days
X_test['days_since_last_review'] = (SCRAPE_DATE - X_test['last_review']).dt.days

# Verificación de las nuevas features
print("Estadísticas de las features temporales en train:")
print(X_train[['host_age_days', 'listing_age_days', 'days_since_last_review']].describe().round(1))

print("\nNulos en las features temporales:")
print(X_train[['host_age_days', 'listing_age_days', 'days_since_last_review']].isna().sum())

"""### Correccion de valores temporales negativos

Detectamos casos con `listing_age_days` y `days_since_last_review` ligeramente negativos (min -1 y -2 días). Esto se debe a discrepancias de zona horaria entre el momento del  scrape y las reviews registradas en hora local de Milán: una review hecha en la madrugada del 23 de septiembre fue capturada cuando ya era ese día en hora italiana, pero la fecha  del scrape de referencia es 22 de septiembre.

Truncamos estos valores a 0 ya que son semánticamente equivalentes a "review del día del scrape".
"""

# Conteo previo de casos afectados
print("Casos con listing_age_days < 0 en train:",
      (X_train['listing_age_days'] < 0).sum())
print("Casos con days_since_last_review < 0 en train:",
      (X_train['days_since_last_review'] < 0).sum())
print("Casos con listing_age_days < 0 en test:",
      (X_test['listing_age_days'] < 0).sum())
print("Casos con days_since_last_review < 0 en test:",
      (X_test['days_since_last_review'] < 0).sum())

# Truncar a 0 los valores negativos
X_train.loc[X_train['listing_age_days'] < 0, 'listing_age_days'] = 0
X_test.loc[X_test['listing_age_days'] < 0, 'listing_age_days'] = 0

X_train.loc[X_train['days_since_last_review'] < 0, 'days_since_last_review'] = 0
X_test.loc[X_test['days_since_last_review'] < 0, 'days_since_last_review'] = 0

# Verificación post-corrección
print("\nDespués de la corrección:")
print(f"  listing_age_days min en train: {X_train['listing_age_days'].min()}")
print(f"  days_since_last_review min en train: {X_train['days_since_last_review'].min()}")
print(f"  listing_age_days min en test: {X_test['listing_age_days'].min()}")
print(f"  days_since_last_review min en test: {X_test['days_since_last_review'].min()}")

"""### n_amenities y n_verifications

Tanto `amenities` como `host_verifications` vienen como strings que representan listas:
- `amenities`: comodidades del alojamiento (WiFi, A/C, cocina, etc.)
- `host_verifications`: métodos de verificación del host (email, teléfono, work_email, etc.)

Como strings crudos no son utilizables por los modelos. Extraemos como features derivadas
la **cantidad de elementos** en cada lista, que sirven como proxies de:
- `n_amenities`: nivel de equipamiento del alojamiento
- `n_verifications`: nivel de validación/confiabilidad del host
"""

print(type(X_train['amenities'].iloc[0]))
print("Primer ejemplo:")
print(X_train['amenities'].iloc[0][:300])
print("\nSegundo ejemplo:")
print(X_train['amenities'].iloc[1][:300])

print(type(X_train['host_verifications'].iloc[0]))
print("Primer ejemplo:")
print(X_train['host_verifications'].iloc[0])
print("\nSegundo ejemplo:")
print(X_train['host_verifications'].iloc[1])

import ast

def contar_elementos(s):
    if pd.isna(s):
        return 0
    return len(ast.literal_eval(s))

# n_amenities
X_train['n_amenities'] = X_train['amenities'].apply(contar_elementos)
X_test['n_amenities'] = X_test['amenities'].apply(contar_elementos)

# n_verifications
X_train['n_verifications'] = X_train['host_verifications'].apply(contar_elementos)
X_test['n_verifications'] = X_test['host_verifications'].apply(contar_elementos)

# Verificación
print("Estadísticas de n_amenities en train:")
print(X_train['n_amenities'].describe().round(1))
print(f"Listings con 0 amenities en train: {(X_train['n_amenities'] == 0).sum()}")

print("\nEstadísticas de n_verifications en train:")
print(X_train['n_verifications'].describe().round(1))
print(f"Listings con 0 verifications en train: {(X_train['n_verifications'] == 0).sum()}")

# Distribución de n_verifications (esperamos un rango chico, típicamente 0-5)
print("\nDistribución de n_verifications:")
print(X_train['n_verifications'].value_counts().sort_index())

"""Dado que en `n_verifications` el 78.8% de los listings tiene exactamente 2 verificaciones y el 95.4% se concentra en solo 2 valores (2 o 3). Este nivel de desbalance es comparable al de `host_has_profile_pic` y `has_availability`, por lo tanto descartamos `n_verifications` y `host_verifications`."""

# Eliminamos n_verifications por baja variabilidad
X_train = X_train.drop(columns=['n_verifications'])
X_test = X_test.drop(columns=['n_verifications'])

X_train = X_train.drop(columns=['host_verifications'])
X_test = X_test.drop(columns=['host_verifications'])

"""### Eliminación de las variables reemplazadas"""

# Columnas originales reemplazadas por features derivadas
cols_reemplazadas = ['host_since', 'first_review', 'last_review', 'amenities']

X_train = X_train.drop(columns=cols_reemplazadas)
X_test = X_test.drop(columns=cols_reemplazadas)

"""### Tratamiento de variables específicas

#### Tratamiento de `host_response_time`

Creamos una variable categórica ordinal que guarda la información de esta variable.

Recordando que existe la variable `has_response_data` que indica si la información almacenada en esta variable es válida o no.

Esta variable es casteada a tipo int con el objetivo de que sea compatible con la regresión lineal y para que aún se puedan mantener las jerarquías por el hecho de ser una variable categórica ordinal.
"""

response_order = {
    'within an hour':     0,
    'within a few hours': 1,
    'within a day':       2,
    'a few days or more': 3,
}

for split in [X_train, X_test]:
    split['host_response_time'] = split['host_response_time'].map(response_order).astype(float)

"""#### Tratamiento de `neighbourhood_cleansed`

Decidimos droppear esta variable debido a que con `latitud` y `longitud` se puede inferir en qué barrio está el AirBnB. Además, al ser una variable categórica de mucha cardinalidad, resulta muy costoso encodearla.
"""

X_train = X_train.drop(columns=['neighbourhood_cleansed'])
X_test  = X_test.drop(columns=['neighbourhood_cleansed'])

"""#### Tratamiento de `property_type`

Como ya analizamos previamente, en `property_type` la mayoría de los valores se concentran en unas pocas categorías. Por esto, decidimos aplicar One-Hot Encoding sobre las categorías más populares(superan el 1% de frecuencia) y colapsar las demás en otra categoría llamada `Other`.

Las categorías de `property_type` más populares son:
1. Entire rental unit - 63.86%
2. Entire condo - 19.30%
3. Private room in rental unit - 5.67%
4. Private room in condo - 2.32%
5. Entire loft - 2.08%
6. Entire home - 1.48%
7. Entire vacation home - 1.21%    
8. Entire serviced apartment - 1.00%
"""

freq = X_train['property_type'].value_counts(normalize=True).mul(100).round(2)
freq_abs = X_train['property_type'].value_counts()

resumen = pd.DataFrame({
    'cantidad': freq_abs,
    'porcentaje': freq,
    'porcentaje_acumulado': freq.cumsum()
})

print(f"Total de categorías: {len(resumen)}")
print(f"Categorías que superan el 1%: {(resumen['porcentaje'] >= 1).sum()}")
print(f"Categorías que NO superan el 1%: {(resumen['porcentaje'] < 1).sum()}")
print(f"Cobertura del top (>=1%): {resumen.loc[resumen['porcentaje'] >= 1, 'porcentaje'].sum():.2f}%\n")

# Creación de la categoría Other
threshold = 0.01
top_types = (
    X_train['property_type']
    .value_counts(normalize=True)
    .loc[lambda x: x >= threshold]
    .index
)

for split in [X_train, X_test]:
    split['property_type'] = split['property_type'].where(
        split['property_type'].isin(top_types), other='Other'
    )

# One-Hot-Encoding sobre las categorías resultantes
X_train = pd.get_dummies(X_train, columns=['property_type'], drop_first=True)
X_test  = pd.get_dummies(X_test,  columns=['property_type'], drop_first=True)
X_test  = X_test.reindex(columns=X_train.columns, fill_value=0)

"""#### Tratamiento de `room_type`

Para esta variable realizamos un OHE clásico ya que es una variable categórica nominal (sin jerarquías) y además son sólo 4 categorías.
"""

X_train = pd.get_dummies(X_train, columns=['room_type'], drop_first=True)
X_test  = pd.get_dummies(X_test,  columns=['room_type'], drop_first=True)
X_test = X_test.reindex(columns=X_train.columns, fill_value=0)

"""### Forma del dataframe luego del tratamiento de las variables"""

X_train.info()

"""## Tratamiento de valores nulos

### Verificación del estado actual de nulos
"""

nulls = X_train.isna().sum()
nulls = nulls[nulls > 0].sort_values(ascending=False)
print((nulls / len(X_train) * 100).round(2).to_string())

"""### Tratamiento de nulos en variables de capacidad

Para las variables `beds`, `bedrooms` y `bathrooms` vamos a utilizar la mediana para imputar los nulos debido a que, al ser muy baja la cantidad de los mismo, la decisión de imputación que tomemos tendrá un impacto mínimo.
"""

cols_residuales = ['bathrooms', 'bedrooms', 'beds']
for col in cols_residuales:
    median_val = X_train[col].median()
    X_train[col] = X_train[col].fillna(median_val)
    X_test[col]  = X_test[col].fillna(median_val)

"""### Tratamiento de nulos por ausencia de reviews

Imputaremos con 0 a los nulos de las variables  `review_scores_rating`, `review_scores_location`, `listing_age_days` y `days_since_last_review` debido a que estos nulos se dan, como se demostró en el análisis exploratorio, porque la propiedad aún no tiene reviews. Esta información queda contenida en la variable `has_reviews`.
"""

cols_sin_reviews = [
    'review_scores_rating', 'review_scores_location',
    'listing_age_days', 'days_since_last_review'
]
for split in [X_train, X_test]:
    split[cols_sin_reviews] = split[cols_sin_reviews].fillna(0)

"""### Tratamiento de nulos por ausencia de datos de respuesta

Al igual que en el apartado anterior, se tiene una variable(`has_responde_data`) que muestra si hay respuestas o no. Por lo que en caso de no haber respuestas, se imputa a `host_response_time` por la moda(recordando que es una categórica ordinal) y a `host_response_rate` con la mediana, ambas obtenidas del dataframe de entrenamiento.
"""

median_rate = X_train['host_response_rate'].median()
X_train['host_response_rate'] = X_train['host_response_rate'].fillna(median_rate)
X_test['host_response_rate']  = X_test['host_response_rate'].fillna(median_rate)

mode_time = X_train['host_response_time'].mode()[0]
X_train['host_response_time'] = X_train['host_response_time'].fillna(mode_time)
X_test['host_response_time']  = X_test['host_response_time'].fillna(mode_time)

"""### Tratamiento de nulos de `host_acceptance_rate`

Se imputan los nulos esta variable, en el dataframe de prueba y de entrenamiento, por la mediana de la misma del dataframe de entrenamiento.
"""

median_acc = X_train['host_acceptance_rate'].median()
X_train['host_acceptance_rate'] = X_train['host_acceptance_rate'].fillna(median_acc)
X_test['host_acceptance_rate']  = X_test['host_acceptance_rate'].fillna(median_acc)

"""### Tratamiento de nulos de `host_age_days`

Para imputar los nulos de esta variable optamos por utilizar la mediana debido a la poca cantidad de valores nulos y, al representar la edad de la cuenta del propietario, consideramos que es una buena estimación
"""

median_val = X_train['host_age_days'].median()
X_train['host_age_days'] = X_train['host_age_days'].fillna(median_val)
X_test['host_age_days']  = X_test['host_age_days'].fillna(median_val)

"""### Verificación final"""

assert X_train.isna().sum().sum() == 0, "Quedan nulos en X_train"
assert X_test.isna().sum().sum()  == 0, "Quedan nulos en X_test"
print("✓ Sin nulos en train ni test")

"""## Escalado

Aplicaremos un escalado usando `StandardScaler`. Esto para mejorar los rendimientos de los modelos.

El escalador "aprenderá" la media y la desviación estándar ajustándose (`fit`) solo sobre el conjunto de entrenamiento (`X_train`). Luego, el mismo escalador se va a aplicar para transformar tanto el conjunto de entrenamiento como el de prueba (`X_test`).
"""

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

scaler.fit(X_train)

X_train_scaled = scaler.transform(X_train)
X_test_scaled  = scaler.transform(X_test)

"""## Modelado

### Regresión Lineal

Primero empezamos con el entrenamiento. Usamos y_train_log como target porque price tiene distribución muy sesgada, mientras que el logaritmo de price tiene una distribucion mas simetrica
"""

from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

lr = LinearRegression()
lr.fit(X_train_scaled, y_train_log)

"""#### Evaluación de métricas"""

# Predicciones en escala log (como fue entrenado el modelo)
y_pred_train_log = lr.predict(X_train_scaled)
y_pred_test_log  = lr.predict(X_test_scaled)

# Conversión a escala USD para métricas interpretables
y_pred_train_usd = np.expm1(np.clip(y_pred_train_log, -10, 15))
y_pred_test_usd  = np.expm1(np.clip(y_pred_test_log,  -10, 15))

def evaluate_model(y_true_usd, y_pred_usd, y_true_log, y_pred_log, split_name):
    # Métricas en escala log
    r2_log   = r2_score(y_true_log, y_pred_log)
    rmse_log = np.sqrt(mean_squared_error(y_true_log, y_pred_log))

    # Métricas en escala USD
    r2_usd   = r2_score(y_true_usd, y_pred_usd)
    rmse_usd = np.sqrt(mean_squared_error(y_true_usd, y_pred_usd))
    mae_usd  = mean_absolute_error(y_true_usd, y_pred_usd)
    mape_usd = np.mean(np.abs((y_true_usd - y_pred_usd) / np.maximum(y_true_usd, 1))) * 100

    print(f"\n{'─'*40}")
    print(f"  {split_name}")
    print(f"{'─'*40}")
    print(f"  ── escala log (operativa) ──────")
    print(f"  R²:    {r2_log:.4f}")
    print(f"  RMSE:  {rmse_log:.4f}")
    print(f"  ── escala USD (interpretable) ──")
    print(f"  R²:    {r2_usd:.4f}")
    print(f"  RMSE:  $ {rmse_usd:.2f}")
    print(f"  MAE:   $ {mae_usd:.2f}")
    print(f"  MAPE:  {mape_usd:.2f}%")

print("=== Regresión Lineal — métricas ===")
evaluate_model(y_train, y_pred_train_usd, y_train_log, y_pred_train_log, "Train")
evaluate_model(y_test,  y_pred_test_usd,  y_test_log,  y_pred_test_log,  "Test")

"""**Performance general:**

| Métrica | Train | Test |
|---|---|---|
| R² (log) | 0.3919 | 0.4144 |
| R² | 0.2627 | 0.3073 |
| RMSE (log) | 0.4408 | 0.4284 |
| RMSE (\$) | \$93.35 | \$90.61 |
| MAE (\$) | \$54.95 | \$53.51 |
| MAPE | 34.98% | 33.83% |

La regresión lineal es un modelo de baja varianza que no memoriza el conjunto de entrenamiento. Su limitación principal es el sesgo: asume relaciones lineales entre features y target, lo que le impide capturar interacciones (por ejemplo, que el efecto de `bedrooms` sobre el precio varía según `room_type`) o efectos no lineales.

Un resultado llamativo es que **test presenta mejores métricas que train** en todas las escalas. Esto puede darse ya que al no memorizar el conjunto de entrenamiento, puede depender de la aleatoriedad del split.

El MAE de ~\$54 sobre una mediana de precio de ~\$125 y un MAPE de ~34% son resultados razonables para un modelo que asume linealidad en un problema que claramente no lo es.

#### Variables mas influyentes

Los coeficientes están calculados sobre features estandarizadas, por lo que son directamente comparables entre sí: un coeficiente de 0.1 significa que un aumento de 1 desvío estándar en esa feature produce un incremento de 0.1 unidades en log(price+1), manteniendo el resto
de las variables constantes.
"""

feature_names = X_train.columns
coefs = pd.Series(lr.coef_, index=feature_names)

top_pos = coefs.nlargest(15)
top_neg = coefs.nsmallest(15)
top_combined = pd.concat([top_neg, top_pos]).sort_values()

fig, ax = plt.subplots(figsize=(11, 9))
colors = ['#EF5350' if c > 0 else '#42A5F5' for c in top_combined.values]
top_combined.plot(kind='barh', ax=ax, color=colors, edgecolor='black', linewidth=0.5)
ax.axvline(0, color='black', linewidth=0.8, linestyle='--')
ax.set_title('Top variables más influyentes — Regresión Lineal\n'
             '(coeficientes estandarizados, target = log(price+1))', fontsize=13)
ax.set_xlabel('Coeficiente (unidades de log(price+1) por desvío estándar del feature)')
ax.set_ylabel('Feature')
plt.tight_layout()
plt.show()

"""**Variable más influyente:** `review_scores_location` tiene el coeficiente positivo más alto, la percepción de ubicación por parte de los huéspedes es el predictor lineal más fuerte del precio, por encima de la capacidad física del alojamiento. `has_reviews` tiene el coeficiente negativo más pronunciado, lo que captura que los listings sin ninguna reseña tienden a tener precios más altos (posiblemente propiedades nuevas o de lujo que aún no acumularon reviews).

#### Análisis de residuos

Analizamos los residuos del modelo sobre el conjunto de test para evaluar si los errores tienen algún patrón sistemático o si se distribuyen de forma aleatoria alrededor del cero.
"""

# Conversión a USD para visualización
y_pred_test_usd = np.expm1(np.clip(y_pred_test_log, -10, 15))
residuals_test  = y_test.values - y_pred_test_usd

fig, axes = plt.subplots(1, 3, figsize=(18, 5))

axes[0].scatter(y_pred_test_usd, residuals_test, alpha=0.3, s=6, color='steelblue')
axes[0].axhline(0, color='red', linestyle='--', linewidth=1)
axes[0].set_xlabel('Predicciones ($)')
axes[0].set_ylabel('Residuo ($)')
axes[0].set_title('Residuos vs. Predicciones (test)')

axes[1].hist(residuals_test, bins=80, color='steelblue', edgecolor='black')
axes[1].set_xlabel('Residuo ($)')
axes[1].set_ylabel('Frecuencia')
axes[1].set_title('Distribución de residuos (test)')

axes[2].scatter(y_test, y_pred_test_usd, alpha=0.3, s=6, color='#66BB6A')
lim = max(y_test.max(), y_pred_test_usd.max())
axes[2].plot([0, lim], [0, lim], 'r--', linewidth=1, label='Predicción perfecta')
axes[2].set_xlabel('Precio real ($)')
axes[2].set_ylabel('Precio predicho ($)')
axes[2].set_title('Real vs. Predicho (test)')
axes[2].legend()

plt.suptitle('Análisis de residuos — Regresión Lineal', fontsize=13)
plt.tight_layout()
plt.show()

"""**Análisis de residuos:**

- **Residuos vs. Predicciones:** se observa un patrón en forma de abanico, aumentando la varianza de los residuos a medida que el precio predicho crece. El modelo es más impreciso cuanto más caro es el alojamiento.

- **Distribución de residuos:** centrada cerca del cero con sesgo a la derecha, lo que sugiere que el modelo tiende a subestimar los precios altos con mayor frecuencia de lo que los sobreestima.

- **Real vs. Predicho:** los puntos siguen la diagonal en el rango bajo-medio (hasta ~\$300), pero se dispersan progresivamente para precios más altos, confirmando que el modelo captura bien los listings baratos pero pierde capacidad predictiva en los más caros.

### XGBoost

Entrenamos sobre `y_train_log` para mantener consistencia con la regresión lineal y trabajar con una distribución más simétrica del target.
"""

from xgboost import XGBRegressor
from sklearn.model_selection import KFold, RandomizedSearchCV, cross_val_score
import joblib

# Modelo base (sin optimizar)
xgb_base = XGBRegressor(
    n_estimators=300,
    random_state=42,
    n_jobs=-1,
    verbosity=0
)
xgb_base.fit(X_train_scaled, y_train_log)

y_pred_train_xgb_base_log = xgb_base.predict(X_train_scaled)
y_pred_test_xgb_base_log  = xgb_base.predict(X_test_scaled)

y_pred_train_xgb_base_usd = np.expm1(np.clip(y_pred_train_xgb_base_log, -10, 15))
y_pred_test_xgb_base_usd  = np.expm1(np.clip(y_pred_test_xgb_base_log,  -10, 15))

print("=== XGBoost — Modelo base (sin optimizar) ===")
evaluate_model(y_train, y_pred_train_xgb_base_usd, y_train_log, y_pred_train_xgb_base_log, "Train")
evaluate_model(y_test,  y_pred_test_xgb_base_usd,  y_test_log,  y_pred_test_xgb_base_log,  "Test")

"""#### Optimización de hiperparámetros

Usamos `RandomizedSearchCV` con validación cruzada `KFold(n_splits=5)` para explorar el espacio de hiperparámetros. Esta estrategia evalúa cada combinación sobre 5 particiones del conjunto de entrenamiento, eligiendo la que minimiza el error cuadrático medio (negado, porque sklearn maximiza el score).

Los hiperparámetros considerados son:
- `n_estimators`: cantidad de árboles en el ensamble.
- `max_depth`: profundidad máxima de cada árbol, controla la complejidad.
- `learning_rate`: shrinkage de la contribución de cada árbol, valores bajos requieren más árboles pero generalizan mejor.
- `subsample`: fracción de filas muestreadas por árbol, reduce overfitting.
- `colsample_bytree`: fracción de features muestreadas por árbol, equivalente al `max_features` de Random Forest.
- `reg_alpha` / `reg_lambda`: regularización L1 y L2 respectivamente.
"""

param_dist_xgb = {
    'n_estimators':      [300, 500, 700],
    'max_depth':         [3, 4, 5],           # reducir complejidad
    'learning_rate':     [0.01, 0.03, 0.05],  # más lento = mejor generalización
    'min_child_weight':  [3, 5, 10],           # mínimo de obs por hoja
    'gamma':             [0, 0.1, 0.5, 1.0],  # penalización por split
    'subsample':         [0.6, 0.7, 0.8],
    'colsample_bytree':  [0.6, 0.7, 0.8],
    'reg_alpha':         [0.1, 1.0, 5.0],
    'reg_lambda':        [5.0, 10.0, 20.0],
}

kf = KFold(n_splits=5, shuffle=True, random_state=42)

xgb_search = RandomizedSearchCV(
    estimator=XGBRegressor(random_state=42, n_jobs=-1, verbosity=0),
    param_distributions=param_dist_xgb,
    n_iter=60,
    scoring='neg_root_mean_squared_error',
    cv=kf,
    random_state=42,
    n_jobs=-1,
    verbose=1
)

xgb_search.fit(X_train_scaled, y_train_log)

print("\nBúsqueda completada")
print(f"Mejor RMSE (log-scale, CV): {-xgb_search.best_score_:.4f}")
print(f"Mejores hiperparámetros:\n{xgb_search.best_params_}")

"""#### Entrenamiento final con los mejores hiperparámetros"""

xgb_best = xgb_search.best_estimator_

y_pred_train_xgb_log = xgb_best.predict(X_train_scaled)
y_pred_test_xgb_log  = xgb_best.predict(X_test_scaled)

# Conversión a USD
y_pred_train_xgb_usd = np.expm1(np.clip(y_pred_train_xgb_log, -10, 15))
y_pred_test_xgb_usd  = np.expm1(np.clip(y_pred_test_xgb_log,  -10, 15))

print("=== XGBoost — Modelo optimizado ===")
evaluate_model(y_train, y_pred_train_xgb_usd, y_train_log, y_pred_train_xgb_log, "Train")
evaluate_model(y_test,  y_pred_test_xgb_usd,  y_test_log,  y_pred_test_xgb_log,  "Test")

p99_test = np.percentile(y_test, 99)
mask_extremos = y_test > p99_test

y_test_log_core     = y_test_log[~mask_extremos]
y_pred_xgb_log_core = y_pred_test_xgb_log[~mask_extremos]
y_test_usd_core     = y_test[~mask_extremos]
y_pred_xgb_usd_core = y_pred_test_xgb_usd[~mask_extremos]

"""#### Interpretación de resultados

**Performance general:**

| Métrica | Train | Test |
|---|---|---|
| R² (log) | 0.7709 | 0.6407 |
| R² | 0.6574 | 0.5235 |
| RMSE (log) | 0.2706 | 0.3356 |
| RMSE (\$) | \$63.63 | \$75.15 |
| MAE (\$) | \$33.48 | \$40.23 |
| MAPE | 19.93% | 24.85% |

El R² en escala log es 0.7709 en train y 0.6407 en test, con un gap de 0.1302. La regularización aplicada (reg_lambda=20, reg_alpha=1, min_child_weight=5, gamma=0.1) redujo el R² train de 0.9623 del modelo base a 0.7709, priorizando la generalización sobre el ajuste.

**Sobre el RMSE en USD:**

Aplica el mismo razonamiento que en regresión lineal.

**Mejora respecto a regresión lineal:**

XGBoost mejora el R² test de 0.3919 a 0.7709 en escala log. Esta mejora proviene de su capacidad para capturar relaciones no lineales e interacciones entre variables que la regresión lineal no puede representar. Por ejemplo, el efecto de `bedrooms` sobre el precio no es constante: en un departamento entero suma mucho más que en una habitación privada.

#### Variables con mayor importancia segun `gain`

Visualizamos las 20 variables con mayor importancia según el criterio `gain` (reducción promedio de la función de pérdida aportada por cada feature en todos los splits donde fue utilizada). Es el criterio más informativo para interpretar el impacto real de cada variable en el modelo.
"""

importances_xgb = pd.Series(
    xgb_best.feature_importances_,
    index=X_train.columns
).sort_values(ascending=False).head(20)

fig, ax = plt.subplots(figsize=(10, 7))
importances_xgb[::-1].plot(
    kind='barh', ax=ax, color='#FF7043', edgecolor='black', linewidth=0.5
)
ax.set_title(
    'Top 20 variables más importantes — XGBoost\n'
    '(criterio: feature_importances_ / gain)',
    fontsize=13
)
ax.set_xlabel('Importancia relativa')
ax.set_ylabel('Feature')
plt.tight_layout()
plt.show()

"""**Variables más importantes:** el tipo de habitación (`room_type_Private room`) y la
capacidad física (`bedrooms`, `bathrooms`, `accommodates`) dominan la importancia,
seguidos por condiciones de reserva (`instant_bookable`). La geolocalización
(`latitude`, `longitude`) aparece en posiciones medias, reflejando que en Milán
la ubicación importa pero el tipo y tamaño del alojamiento son los determinantes primarios.

#### Análisis de residuos
"""

residuals_xgb = y_test.values - np.expm1(y_pred_test_xgb_log)
mask_viz = (y_test.values <= p99_test) & (np.expm1(y_pred_test_xgb_log) <= p99_test)

fig, axes = plt.subplots(1, 3, figsize=(18, 5))

axes[0].scatter(np.expm1(y_pred_test_xgb_log)[mask_viz],
                residuals_xgb[mask_viz], alpha=0.3, s=6, color='#FF7043')
axes[0].axhline(0, color='red', linestyle='--', linewidth=1)
axes[0].set_xlabel('Predicciones ($)')
axes[0].set_ylabel('Residuo ($)')
axes[0].set_title(f'Residuos vs. Predicciones — zoom ≤ ${p99_test:.0f} (p99)')

axes[1].hist(residuals_xgb[mask_viz], bins=60, color='#FF7043', edgecolor='black')
axes[1].set_xlabel('Residuo ($)')
axes[1].set_ylabel('Frecuencia')
axes[1].set_title(f'Distribución de residuos — zoom ≤ ${p99_test:.0f} (p99)')

axes[2].scatter(y_test.values[mask_viz],
                np.expm1(y_pred_test_xgb_log)[mask_viz],
                alpha=0.3, s=6, color='#FF7043')
axes[2].plot([0, p99_test], [0, p99_test], 'r--', linewidth=1, label='Predicción perfecta')
axes[2].set_xlabel('Precio real ($)')
axes[2].set_ylabel('Precio predicho ($)')
axes[2].set_title(f'Real vs. Predicho — zoom ≤ ${p99_test:.0f} (p99)')
axes[2].legend()

plt.suptitle(f'Análisis de residuos — XGBoost '
             f'(zoom al 99% del test, n={mask_viz.sum()} obs.)', fontsize=13)
plt.tight_layout()
plt.show()

"""### Random Forest

Elegimos Random Forest como tercer modelo por su valor comparativo respecto a XGBoost: mientras XGBoost construye árboles de forma **secuencial** (cada árbol corrige los errores del anterior), Random Forest los construye de forma **paralela e independiente**, promediando sus predicciones. Esta diferencia, *boosting* vs *bagging*, permite evaluar si el problema se beneficia más de la corrección iterativa de errores o de la reducción de varianza por promediado.
"""

from sklearn.ensemble import RandomForestRegressor

# Modelo base (sin optimizar)
rf_base = RandomForestRegressor(
    n_estimators=200,
    random_state=42,
    n_jobs=-1
)
rf_base.fit(X_train_scaled, y_train_log)

y_pred_train_rf_base_log = rf_base.predict(X_train_scaled)
y_pred_test_rf_base_log  = rf_base.predict(X_test_scaled)

# Conversión a USD
y_pred_train_rf_base_usd = np.expm1(np.clip(y_pred_train_rf_base_log, -10, 15))
y_pred_test_rf_base_usd  = np.expm1(np.clip(y_pred_test_rf_base_log,  -10, 15))

print("=== Random Forest — Modelo base (sin optimizar) ===")
evaluate_model(y_train, y_pred_train_rf_base_usd, y_train_log, y_pred_train_rf_base_log, "Train")
evaluate_model(y_test,  y_pred_test_rf_base_usd,  y_test_log,  y_pred_test_rf_base_log,  "Test")

"""#### Optimización de hiperparámetros

Usamos `RandomizedSearchCV` con `KFold(n_splits=5)`, el mismo esquema de validación cruzada aplicado en XGBoost para que los resultados sean comparables entre modelos.

Los hiperparámetros explorados son:
- `n_estimators`: cantidad de árboles. Más árboles reducen varianza con rendimientos decrecientes.
- `max_depth`: profundidad máxima. `None` permite crecer hasta hojas puras (puede overfit).
- `max_features`: fracción de features evaluadas en cada split.
- `min_samples_split` / `min_samples_leaf`: granularidad mínima de los splits, actúan como regularización implícita equivalente a `min_child_weight` en XGBoost.
- `bootstrap`: si se muestrea con reemplazo o no.
"""

from sklearn.model_selection import RandomizedSearchCV, KFold

param_dist_rf = {
    'n_estimators':      [200, 300, 500],
    'max_depth':         [10, 15, 20],
    'max_features':      ['sqrt', 'log2', 0.3],
    'min_samples_split': [5, 10, 20],
    'min_samples_leaf':  [2, 4, 8],
    'bootstrap':         [True],
}

kf = KFold(n_splits=5, shuffle=True, random_state=42)

rf_search = RandomizedSearchCV(
    estimator=RandomForestRegressor(random_state=42, n_jobs=-1),
    param_distributions=param_dist_rf,
    n_iter=40,
    scoring='neg_root_mean_squared_error',
    cv=kf,
    random_state=42,
    n_jobs=-1,
    verbose=1
)

rf_search.fit(X_train_scaled, y_train_log)

print("\nBúsqueda completada")
print(f"Mejor RMSE (log-scale, CV): {-rf_search.best_score_:.4f}")
print(f"Mejores hiperparámetros:\n{rf_search.best_params_}")

"""#### Entrenamiento final con los mejores hiperparámetros"""

rf_best = rf_search.best_estimator_

y_pred_train_rf_log = rf_best.predict(X_train_scaled)
y_pred_test_rf_log  = rf_best.predict(X_test_scaled)

# Conversión a USD
y_pred_train_rf_usd = np.expm1(np.clip(y_pred_train_rf_log, -10, 15))
y_pred_test_rf_usd  = np.expm1(np.clip(y_pred_test_rf_log,  -10, 15))

print("=== Random Forest — Modelo optimizado ===")
evaluate_model(y_train, y_pred_train_rf_usd, y_train_log, y_pred_train_rf_log, "Train")
evaluate_model(y_test,  y_pred_test_rf_usd,  y_test_log,  y_pred_test_rf_log,  "Test")

# Métricas sobre el 99% del test
mask_extremos_rf   = y_test > p99_test
y_test_log_core_rf = y_test_log[~mask_extremos_rf]
y_pred_rf_log_core = y_pred_test_rf_log[~mask_extremos_rf]
y_test_usd_core_rf = y_test[~mask_extremos_rf]
y_pred_rf_usd_core = y_pred_test_rf_usd[~mask_extremos_rf]

"""#### Interpretación de resultados

**Performance general:**

| Métrica | Train | Test |
|---|---|---|
| R² (log) | 0.8870 | 0.5986 |
| R² | 0.7710 | 0.4492 |
| RMSE (log) | 0.1901 | 0.3547 |
| RMSE (\$) | \$52.03 | \$80.80 |
| MAE (\$) | \$24.23 | \$43.22 |
| MAPE | 13.57% | 26.65% |

El R² en escala log es 0.887 en train y 0.599 en test, con un gap de 0.288, comparable al de XGBoost (0.130), pero con un nivel absoluto de performance en test superior.

La configuración encontrada (n_estimators=300, max_depth=20, max_features=0.3,
min_samples_leaf=2, bootstrap=True) logra un balance adecuado entre ajuste y
generalización: el R² train de 0.887 indica que el modelo no memorizó el conjunto de entrenamiento, a diferencia de la configuración inicial sin restricciones donde alcanzó R² train = 0.9440.

**Sobre el R² USD en test:**

A diferencia de XGBoost y la regresión lineal, Random Forest muestra un R² USD en test de 0.4492 sin estar severamente distorsionado por los outliers extremos. Esto se debe a que el promediado de múltiples árboles produce predicciones más conservadoras para precios fuera del rango de entrenamiento.

**Comparación con XGBoost:**

XGBoost supera a Random Forest en todas las métricas de test: R² log 0.641 vs 0.599, MAE $40 vs $43, RMSE $75 vs $81. Además, Random Forest presenta un gap train-test mayor (0.288 vs 0.130 en R² log), lo que indica que está mas
sobreajustado al conjunto de entrenamiento.

#### Features mas importantes
"""

importances_rf = pd.Series(
    rf_best.feature_importances_,
    index=X_train.columns
).sort_values(ascending=False).head(20)

fig, ax = plt.subplots(figsize=(10, 7))
importances_rf[::-1].plot(
    kind='barh', ax=ax, color='#66BB6A', edgecolor='black', linewidth=0.5
)
ax.set_title(
    'Top 20 variables más importantes — Random Forest\n'
    '(criterio: mean decrease in impurity)',
    fontsize=13
)
ax.set_xlabel('Importancia relativa')
ax.set_ylabel('Feature')
plt.tight_layout()
plt.show()

"""#### Análisis de residuos"""

y_pred_test_rf_usd = np.expm1(np.clip(y_pred_test_rf_log, -10, 15))
residuals_rf = y_test.values - y_pred_test_rf_usd
mask_viz_rf  = (y_test.values <= p99_test) & (y_pred_test_rf_usd <= p99_test)

fig, axes = plt.subplots(1, 3, figsize=(18, 5))

axes[0].scatter(y_pred_test_rf_usd[mask_viz_rf], residuals_rf[mask_viz_rf],
                alpha=0.3, s=6, color='#66BB6A')
axes[0].axhline(0, color='red', linestyle='--', linewidth=1)
axes[0].set_xlabel('Predicciones ($)')
axes[0].set_ylabel('Residuo ($)')
axes[0].set_title(f'Residuos vs. Predicciones — zoom ≤ ${p99_test:.0f} (p99)')

axes[1].hist(residuals_rf[mask_viz_rf], bins=60, color='#66BB6A', edgecolor='black')
axes[1].set_xlabel('Residuo ($)')
axes[1].set_ylabel('Frecuencia')
axes[1].set_title(f'Distribución de residuos — zoom ≤ ${p99_test:.0f} (p99)')

axes[2].scatter(y_test.values[mask_viz_rf], y_pred_test_rf_usd[mask_viz_rf],
                alpha=0.3, s=6, color='#66BB6A')
axes[2].plot([0, p99_test], [0, p99_test], 'r--', linewidth=1, label='Predicción perfecta')
axes[2].set_xlabel('Precio real ($)')
axes[2].set_ylabel('Precio predicho ($)')
axes[2].set_title(f'Real vs. Predicho — zoom ≤ ${p99_test:.0f} (p99)')
axes[2].legend()

plt.suptitle(
    f'Análisis de residuos — Random Forest '
    f'(zoom al 99% del test, n={mask_viz_rf.sum()} obs.)',
    fontsize=13
)
plt.tight_layout()
plt.show()

"""## Comparación final

### Tabla comparativa de métricas
"""

tabla_completa = pd.DataFrame({
    'Modelo':      ['Regresión Lineal', 'XGBoost', 'Random Forest'],
    'R² log Train': [0.3919, 0.7709, 0.8870],
    'R² log Test':  [0.4144, 0.6407, 0.5986],
    'Gap (R² log)': [round(0.3919 - 0.4144, 4),
                     round(0.7709 - 0.6407, 4),
                     round(0.8870 - 0.5986, 4)],
    'R² USD Test':  [0.3073, 0.5235, 0.4492],
    'RMSE ($) Test':[90.61,  75.15,  80.80],
    'MAE ($) Test': [53.51,  40.23,  43.22],
    'MAPE Test':    ['33.83%', '24.85%', '26.65%'],
})
tabla_completa = tabla_completa.set_index('Modelo')
print(tabla_completa.to_string())

# Visualización como figura
fig, ax = plt.subplots(figsize=(14, 2.8))
ax.axis('off')

tabla_reset = tabla_completa.reset_index()
col_labels = tabla_reset.columns.tolist()
cell_text  = tabla_reset.values.tolist()

tbl = ax.table(
    cellText=cell_text,
    colLabels=col_labels,
    loc='center',
    cellLoc='center'
)
tbl.auto_set_font_size(False)
tbl.set_fontsize(9.5)
tbl.scale(1.2, 2.0)

# Header
for j in range(len(col_labels)):
    tbl[0, j].set_facecolor('#1565C0')
    tbl[0, j].set_text_props(color='white', fontweight='bold')

# Colores por modelo
colores_filas = ['#E3F2FD', '#FBE9E7', '#E8F5E9']
for i in range(1, 4):
    for j in range(len(col_labels)):
        tbl[i, j].set_facecolor(colores_filas[i - 1])

ax.set_title('Comparación de métricas — Test completo (escala original USD)',
             fontsize=11, fontweight='bold', pad=12)
plt.tight_layout()
plt.show()

"""### Comparación visual — R² log y MAE en test"""

modelos      = ['Regresión\nLineal', 'XGBoost', 'Random\nForest']
r2_log_test  = [0.4144, 0.6407, 0.5986]
mae_test     = [53.51,  40.23,  43.22]
colores_bars = ['#42A5F5', '#FF7043', '#66BB6A']

fig, axes = plt.subplots(1, 2, figsize=(12, 5))

# R² log Test
bars0 = axes[0].bar(modelos, r2_log_test, color=colores_bars,
                    edgecolor='black', linewidth=0.7)
axes[0].set_ylim(0, 0.85)
axes[0].set_title('R² (escala log) — Test', fontsize=12)
axes[0].set_ylabel('R² (log)')
axes[0].set_xlabel("Modelo")
for bar, val in zip(bars0, r2_log_test):
    axes[0].text(bar.get_x() + bar.get_width() / 2,
                 bar.get_height() + 0.01,
                 f'{val:.4f}', ha='center', va='bottom',
                 fontsize=10, fontweight='bold')

# MAE Test
bars1 = axes[1].bar(modelos, mae_test, color=colores_bars,
                    edgecolor='black', linewidth=0.7)
axes[1].set_title('MAE ($) — Test', fontsize=12)
axes[1].set_ylabel('MAE (USD)')
axes[1].set_xlabel("Modelo")
for bar, val in zip(bars1, mae_test):
    axes[1].text(bar.get_x() + bar.get_width() / 2,
                 bar.get_height() + 0.4,
                 f'${val:.2f}', ha='center', va='bottom',
                 fontsize=10, fontweight='bold')

plt.suptitle('Comparación de modelos — métricas en Test', fontsize=13, fontweight='bold')
plt.tight_layout()
plt.show()

"""### Gap train-test - análisis de overfitting"""

r2_log_train = [0.3919, 0.7709, 0.8870]
x     = range(len(modelos))
width = 0.35

fig, ax = plt.subplots(figsize=(10, 5))
b1 = ax.bar([i - width/2 for i in x], r2_log_train, width,
            label='Train', color='#90CAF9', edgecolor='black')
b2 = ax.bar([i + width/2 for i in x], r2_log_test,  width,
            label='Test',  color='#1565C0', edgecolor='black')

ax.set_xticks(list(x))
ax.set_xticklabels(modelos)
ax.set_ylim(0, 1.05)
ax.set_ylabel('R² (escala log)')
ax.set_xlabel("Modelo")
ax.set_title('R² log Train vs Test — análisis de overfitting', fontsize=12)
ax.legend()

for bar in list(b1) + list(b2):
    ax.text(bar.get_x() + bar.get_width() / 2,
            bar.get_height() + 0.01,
            f'{bar.get_height():.3f}',
            ha='center', va='bottom', fontsize=9)

plt.tight_layout()
plt.show()

"""### Conclusión: qué modelo elegimos para predecir el precio?

**Modelo elegido: XGBoost**

La elección se basa en el análisis conjunto de tres criterios: performance en test, control del overfitting y consistencia entre métricas.

**Performance en test.** XGBoost obtiene el mejor R² log en test (0.641), el menor MAE (40.23) y el menor MAPE (24.85%) entre los tres modelos. Esto significa que, en promedio, el modelo se equivoca en aproximadamente \$40 por predicción sobre el mercado típico de Milán.

**Control del overfitting.** El gap train-test de XGBoost en R² log es 0.130, el menor de los tres modelos. Regresión Lineal muestra el fenómeno inverso (test > train, consecuencia del filtrado de outliers), y Random Forest presenta un gap de 0.288. Un gap menor indica que el modelo aprendió patrones generalizables del mercado en lugar de memorizar el conjunto de entrenamiento. La optimización de hiperparámetros fue determinante: los parámetros de regularización (reg_lambda=20, reg_alpha=1, min_child_weight=5, gamma=0.1) redujeron el R² train de 0.962 del modelo base a 0.771, y así no hubo overfitting.

**Consistencia entre métricas.** XGBoost es el modelo que lidera simultáneamente en R² log, R² USD, MAE y MAPE en test. Random Forest es competitivo (R² log test de 0.599, MAE \$43) pero no supera a XGBoost en ninguna métrica de test. Regresión Lineal, como era esperable, tiene la performance más baja y el mayor error promedio (\$53.51 de MAE).

## Guardado de modelos y dataset procesado
"""

import joblib

# Guardado del scaler (necesario para reproducir predicciones)
joblib.dump(scaler, "TA047R_TP1_GRUPO02_EJ3_scaler.pkl")

# Modelo 1 — Regresión Lineal
joblib.dump(lr, "TA047R_TP1_GRUPO02_EJ3_modelo_regresion_lineal.pkl")

# Modelo 2 — XGBoost (optimizado)
joblib.dump(xgb_best, "TA047R_TP1_GRUPO02_EJ3_modelo_xgboost.pkl")

# Modelo 3 — Random Forest (optimizado)
joblib.dump(rf_best, "TA047R_TP1_GRUPO02_EJ3_modelo_random_forest.pkl")

# Dataset procesado (sin columnas eliminadas, sin outliers, con features de ingeniería)
df.to_csv("TA047R_TP1_GRUPO02_EJ3_listings_milan_procesado.csv", index=False)

# Verificación
print("Archivos guardados:")
import os
archivos = [
    "TA047R_TP1_GRUPO02_EJ3_scaler.pkl",
    "TA047R_TP1_GRUPO02_EJ3_modelo_regresion_lineal.pkl",
    "TA047R_TP1_GRUPO02_EJ3_modelo_xgboost.pkl",
    "TA047R_TP1_GRUPO02_EJ3_modelo_random_forest.pkl",
    "TA047R_TP1_GRUPO02_EJ3_listings_milan_procesado.csv",
]
for f in archivos:
    size = os.path.getsize(f) / 1024
    print(f"  {f}  →  {size:.1f} KB")